{
 "title": "Azure Digital Twins",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ADT",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "dimensionFilters": [],
      "metricName": "ApiRequests",
      "metricNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.digitaltwins/digitalTwinsInstances",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ADT",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twin Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "dimensionFilters": [],
      "metricName": "TwinCount",
      "metricNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.digitaltwins/digitalTwinsInstances",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ADT",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "API Requests - Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "dimensionFilters": [],
      "metricName": "ApiRequestsLatency",
      "metricNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.digitaltwins/digitalTwinsInstances",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ADT",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Model Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "dimensionFilters": [],
      "metricName": "ModelCount",
      "metricNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.digitaltwins/digitalTwinsInstances",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ADT",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "API Requests - Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "dimensionFilters": [],
      "metricName": "ApiRequestsFailureRate",
      "metricNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.digitaltwins/digitalTwinsInstances",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ADT",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "API Requests - 429 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "metricName": "ApiRequests",
      "metricNamespace": "microsoft.digitaltwins/digitaltwinsinstances",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.digitaltwins/digitalTwinsInstances",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ADT",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}