{
 "title": "Connector Reliability Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AllSubscriptions" },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "AppInsightsInstance",
    "label": "App Insights Instance",
    "query": {}
   },
   {
    "name": "FullCustomerInstanceName",
    "query": {}
   },
   {
    "name": "Connector",
    "query": {}
   },
   {
    "name": "EdgeDeviceName",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Connectors Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trending %",
   "type": "stat",
   "description": "Percentage of capabilities trending over expected",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expression": "($ActualCount / $EnabledTwins) * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Active Capabilities",
   "type": "stat",
   "description": "Capabilities in ADT that are enabled for data collection",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-EnabledCapabilitiesCount",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Trending Capabilities",
   "type": "stat",
   "description": "Received telemetry from capabilities modelled in ADT",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-TelemetryModelledCountForPartialAlert",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Total Telemetry Count",
   "type": "stat",
   "description": "Total telemetry received in ADX for selected time range",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-TelemetryValuesCount",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Collection Interval",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-ConnectorInterval",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Enabled Capabilities",
   "type": "timeseries",
   "description": "- Number of capability twins with Enabled flag set in ADT",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ConnectorName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-EnabledCapabilitiesCount",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Telemetry Received for enabled capabilities",
   "type": "timeseries",
   "description": "Total telemetry events received for capabilities that are enabled",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ConnectorName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-TelemetryADTModelledCount",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Active Twins",
   "type": "timeseries",
   "description": "Total twins configured for this connector in ADT",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ConnectorName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-ActiveTwinsCount",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Total Telemetry Received",
   "type": "timeseries",
   "description": "Total telemetry events received for this connector",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{ConnectorName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "ConnectorName", "filters": [ "$Connector" ], "operator": "eq" }
      ],
      "metricName": "Willow.ConnectorReliabilityMonitor-TelemetryValuesCount",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Edge Device Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connectors",
     "type": "table",
     "description": "List of connectors deployed",
     "gridPos": { "h": 19, "w": 4, "x": 0, "y": 29 },
     "targets": [
      {
       "azureLogAnalytics": {
        "query": "customMetrics\r\n| where name == \"EdgeMetrics-UsedMemoryBytes\"\r\n| extend dimensions=parse_json(customDimensions)\r\n| extend device = tostring(dimensions.edge_device)\r\n| where device == '$EdgeDeviceName'\r\n| extend module = tostring(dimensions.module_name)\r\n| where not (module has_any(\"host\", \"MetricsCollectorModule\", \"edgeAgent\",\"edgeHub\",\"CASBACnetRPC\",\"MenderRestart\"))\r\n| summarize by module = replace_regex(module,'-([A-Za-z0-9]*)ConnectorModule$','')\r\n| order by module asc",
        "resources": [
         "/subscriptions/$Subscription/resourceGroups/$ResourceGroup/providers/microsoft.insights/components/$AppInsightsInstance"
        ],
        "resultFormat": "table"
       },
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [],
        "metricName": "EdgeMetrics-UsedMemoryBytes",
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "$Region",
          "resourceGroup": "$ResourceGroup",
          "resourceName": "$AppInsightsInstance",
          "subscription": "$Subscription"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$Subscription"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Host uptime refers to the time during which Host OS is operational, whereas IoTEdge Daemon uptime refers to the time during which Edge runtime is operational.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [
         { "dimension": "edge_device", "filters": [ "$EdgeDeviceName" ], "operator": "eq" }
        ],
        "metricName": "EdgeMetrics-HostUptimeSeconds",
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "$Region",
          "resourceGroup": "$ResourceGroup",
          "resourceName": "$AppInsightsInstance",
          "subscription": "$Subscription"
         }
        ],
        "timeGrain": "auto",
        "top": "50"
       },
       "subscription": "$Subscription"
      },
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [
         { "dimension": "edge_device", "filters": [ "$EdgeDeviceName" ], "operator": "eq" }
        ],
        "metricName": "EdgeMetrics-EdgeUptimeSeconds",
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "$Region",
          "resourceGroup": "$ResourceGroup",
          "resourceName": "$AppInsightsInstance",
          "subscription": "$Subscription"
         }
        ],
        "timeGrain": "auto",
        "top": "50"
       },
       "subscription": "$Subscription"
      }
     ]
    },
    {
     "title": "Device Usage",
     "type": "bargauge",
     "description": "CPU, Memory and Disk usage of the Edge Device (Trustbox / VM)",
     "gridPos": { "h": 6, "w": 7, "x": 8, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [
         { "dimension": "module_name", "filters": [ "host" ], "operator": "eq" },
         { "dimension": "edge_device", "filters": [ "$EdgeDeviceName" ], "operator": "eq" }
        ],
        "metricName": "EdgeMetrics-UsedCpuPercent",
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "$Region",
          "resourceGroup": "$ResourceGroup",
          "resourceName": "$AppInsightsInstance",
          "subscription": "$Subscription"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$Subscription"
      },
      { "expression": "($MemoryUsed/$MemoryTotal)*100", "type": "math" },
      {
       "expression": "(($TotalDiskSpace - $AvailableDiskSpace)/$TotalDiskSpace)*100",
       "type": "math"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "description": "CPU usage of each edge module deployed on a device",
     "gridPos": { "h": 13, "w": 5, "x": 4, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "range" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "{{module_name}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [
         { "dimension": "module_name", "filters": [ "host" ], "operator": "ne" },
         { "dimension": "edge_device", "filters": [ "$EdgeDeviceName" ], "operator": "eq" }
        ],
        "metricName": "EdgeMetrics-UsedCpuPercent",
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "$Region",
          "resourceGroup": "$ResourceGroup",
          "resourceName": "$AppInsightsInstance",
          "subscription": "$Subscription"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$Subscription"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "bargauge",
     "description": "Memory usage of each edge module deployed on a device",
     "gridPos": { "h": 13, "w": 6, "x": 9, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "range" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "{{module_name}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [
         { "dimension": "edge_device", "filters": [ "$EdgeDeviceName" ], "operator": "eq" },
         { "dimension": "module_name", "filters": [ "host" ], "operator": "ne" }
        ],
        "metricName": "EdgeMetrics-UsedMemoryBytes",
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "$Region",
          "resourceGroup": "$ResourceGroup",
          "resourceName": "$AppInsightsInstance",
          "subscription": "$Subscription"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "$Subscription"
      }
     ]
    }
   ]
  }
 ]
}