{
 "title": "Elastic Pools",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "ElasticPool",
    "label": "Elastic Pool",
    "query": {}
   },
   {
    "name": "EP",
    "label": "Pool",
    "query": {}
   },
   {
    "name": "Database",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Max Percent DTU Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Average Percent DTU Used By Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/databases",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$Database",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Max DTUs Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "eDTU_limit",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Max Percent DTU Used By Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "microsoft.sql/servers/databases",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/databases",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$Database",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Max DTUs Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "eDTU_used",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Data space user percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Data IO Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "physical_data_read_percent",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "SQL Instance Memory Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "sql_instance_memory_percent",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "SQL Instance CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "sql_instance_cpu_percent",
      "metricNamespace": "microsoft.sql/servers/elasticpools",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.sql/servers/elasticpools",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ElasticPool",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}