{
 "title": "Event Hub",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "EventHub",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "IncomingRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Throttled Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "User Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Quota Exceeded Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "QuotaExceededErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "NamespaceMemoryUsage",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "NamespaceCpuUsage",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}