{
 "title": "Event Grid",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "EventGridNamespace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Successful Publish Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulPublishedEvents",
      "metricNamespace": "microsoft.eventgrid/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventGrid/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventGridNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Failed Publish Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FailedPublishedEvents",
      "metricNamespace": "microsoft.eventgrid/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventGrid/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventGridNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Successful Received Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulReceivedEvents",
      "metricNamespace": "microsoft.eventgrid/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventGrid/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventGridNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Successful Received Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SuccessfulReceivedEvents",
      "metricNamespace": "microsoft.eventgrid/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventGrid/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventGridNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Publish Operations Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "PublishLatencyInMilliseconds",
      "metricNamespace": "microsoft.eventgrid/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventGrid/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventGridNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Receive Operations Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ReceiveLatencyInMilliseconds",
      "metricNamespace": "microsoft.eventgrid/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventGrid/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$EventGridNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}