{
 "title": "Exceptions",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ApplicationInsightsInstance",
    "label": "Application Insights Instance",
    "query": "ain-dev-eus, ain-dev-aue,ain-prd-eus2 ,ain-prd-weu,ain-prd-aue"
   },
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   { "name": "Environment", "query": "prd,dev" },
   { "name": "RegionShortName", "query": "aue,eus,eus2,weu" },
   {
    "name": "Stamp",
    "query": {}
   },
   {
    "name": "CustomerInstance",
    "label": "Customer Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "From Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Exceptions Over Time",
   "type": "timeseries",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| summarize Count=count() by bin(TimeGenerated,1m), Environment, Region, Stamp, Instance, AppRoleName\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, AppRoleName, Count\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions By App Role Instance",
   "type": "barchart",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| summarize Count=count() by bin(TimeGenerated,1m), Environment, Region, Stamp, Instance, AppRoleName\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, AppRoleName, Count\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions By App Role Name",
   "type": "timeseries",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| summarize Count=count() by bin(TimeGenerated,1m), Environment, Region, Stamp, Instance, AppRoleName\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, AppRoleName, Count\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  { "title": "From Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Exceptions By App Role Name",
   "type": "barchart",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$RegionShortName:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$CustomerInstance:csv\" has Instance\r\n| summarize Count=count() by bin(TimeGenerated,1m), AppRoleName\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, AppRoleName, Count\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions By App Role Name",
   "type": "table",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$RegionShortName:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$CustomerInstance:csv\" has Instance\r\n| summarize Count=count() by AppRoleName\r\n| order by Count desc, AppRoleName asc\r\n\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions By App Role Instance",
   "type": "barchart",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$RegionShortName:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$CustomerInstance:csv\" has Instance\r\n| summarize Count=count() by bin(TimeGenerated,1m), Environment, Region, Stamp, Instance, AppRoleName\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, AppRoleName, Count\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions By App Role Instance",
   "type": "table",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$RegionShortName:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$CustomerInstance:csv\" has Instance\r\n| summarize Count=count() by Environment, Region, Stamp, Instance, AppRoleName\r\n| order by Count desc\r\n\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions By Type",
   "type": "barchart",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$RegionShortName:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$CustomerInstance:csv\" has Instance\r\n| summarize Count=count() by bin(TimeGenerated,1m), Environment, Region, ExceptionType\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, ExceptionType, Count\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Socket Exceptions By Type",
   "type": "barchart",
   "description": "Exceptions for All Apps",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppExceptions\r\n| where ExceptionType contains \"socket\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$RegionShortName:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$CustomerInstance:csv\" has Instance\r\n| summarize Count=count() by bin(TimeGenerated,1m), Environment, Region, ExceptionType\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, ExceptionType, Count\r\n\r\n\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "cloud/roleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ApplicationInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}