{
 "title": "Ingestion Pipeline Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AppInsightsInstance",
    "label": "App Insights Instance",
    "query": "ain-dev-eus,ain-dev-aue,ain-prd-eus2,ain-prd-weu,ain-prd-aue"
   },
   { "name": "AllSubscriptions" },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "AppName",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages Processed Status by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}} {{MessageProcessingStatus}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "MessageProcessingStatus",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" }
      ],
      "metricName": "MessagesProcessed",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Successful Messages Processed by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "MessageProcessingStatus", "filters": [ "Success" ], "operator": "eq" },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "MessagesProcessed",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Skipped Messages Processed by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "MessageProcessingStatus", "filters": [ "Skipped" ], "operator": "eq" },
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" }
      ],
      "metricName": "MessagesProcessed",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Failed Messages Processed by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "MessageProcessingStatus", "filters": [ "Failed" ], "operator": "eq" },
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" }
      ],
      "metricName": "MessagesProcessed",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  { "title": "Mapped Telemetry Adaptor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Percentage of cache miss to processed messages",
   "type": "timeseries",
   "description": "Percentage of processed messages to missed cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  { "title": "Telemetry Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Telemetry Streaming - Connect",
   "type": "timeseries",
   "description": "MQTT Connect",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [
         "Willow.LiveData.TelemetryStreaming"
        ],
        "operator": "eq"
       },
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "TelemetryStreaming-Connect",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Telemetry Streaming - Disconnect",
   "type": "timeseries",
   "description": "MQTT Disconnect",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [
         "Willow.LiveData.TelemetryStreaming"
        ],
        "operator": "eq"
       },
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "TelemetryStreaming-Disconnect",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}