{
 "title": "IoT Services App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AllSubscriptions" },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "AppInsightsInstance",
    "label": "App Insights Instance",
    "query": {}
   },
   {
    "name": "FullCustomerInstanceName",
    "query": {}
   },
   {
    "name": "ContainerEnvironmentId",
    "query": {}
   },
   {
    "name": "ContainerEnvironment",
    "query": {}
   },
   {
    "name": "AppName",
    "query": "cognian-telemetry-adapter, command-and-control-web, connector-reliability-monitor, connectorcore, connectorxl, edge-deployment-dashboard, edge-deployment-db-sync-service, edge-deployment-service, edge-metrics-processor, iothub-telemetry-adaptor, livedatacore, mapped-telemetry-adaptor, telemetry-streaming"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   { "name": "ns", "query": "microsoft.app/containerapps" },
   {
    "name": "EventHub",
    "query": {}
   },
   {
    "name": "AppRoleName",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Allocated CPU (m cores)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources\r\n| where subscriptionId =~ '$sub'\r\n| where resourceGroup =~ '$rg'\r\n| where type =~ '$ns'\r\n| where name =~ '$AppName'\r\n| extend containers = todynamic(properties.template.containers)\r\n| mv-expand containers\r\n| summarize cpu = strcat(sum(todouble(containers.resources.cpu)) * 1000, \" m cores\")"
     },
     "subscription": "a5c27c0c-35f5-488f-9a2f-93e06c2eb56f",
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Max Allocated Memory (MB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources\r\n| where subscriptionId =~ '$sub'\r\n| where resourceGroup =~ '$rg'\r\n| where type =~ '$ns'\r\n| where name =~ '$AppName'\r\n| extend containers = todynamic(properties.template.containers)\r\n| mv-expand containers\r\n| summarize memory = strcat(\r\n      sum(\r\n        todouble(substring(containers.resources.memory, 0, strlen(containers.resources.memory) - 2)) \r\n        * 1000\r\n      ), \r\n    \" MB\")"
     },
     "subscription": "a5c27c0c-35f5-488f-9a2f-93e06c2eb56f",
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Avg CPU Usage (m cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UsageNanoCores",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$AppName",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$AppName",
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Memory Working Set Bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "WorkingSetBytes",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$AppName",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$AppName",
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "API Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Server Request Duration - By App Role Name - $FullCustomerInstanceName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "AppRoleName", "filters": [ "$AppRoleName" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Count - By App Role Name - $FullCustomerInstanceName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "AppRoleName", "filters": [ "$AppRoleName" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  { "title": "Ingestion Pipeline Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.eventhub/namespaces",
        "region": "$Region",
        "resourceGroup": "$rg",
        "resourceName": "$EventHub",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.eventhub/namespaces",
        "region": "$Region",
        "resourceGroup": "$rg",
        "resourceName": "$EventHub",
        "subscription": "$sub"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failed Messages Processed by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "MessageProcessingStatus", "filters": [ "Failed" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "AppRoleName", "filters": [ "$AppRoleName" ], "operator": "eq" }
      ],
      "metricName": "MessagesProcessed",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Skipped Messages Processed by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "AppRoleName", "filters": [ "$AppRoleName" ], "operator": "eq" },
       { "dimension": "MessageProcessingStatus", "filters": [ "Skipped" ], "operator": "eq" }
      ],
      "metricName": "MessagesProcessed",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Parse Error Messages by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "MessageProcessingStatus", "filters": [ "ParseError" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" },
       { "dimension": "AppRoleName", "filters": [ "$AppRoleName" ], "operator": "eq" }
      ],
      "metricName": "MessagesProcessed",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  { "title": "Mapped Telemetry Adaptor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Percentage of cache miss to processed messages",
   "type": "timeseries",
   "description": "Percentage of processed messages to missed cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  { "title": "Telemetry Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Telemetry Streaming - Connect",
   "type": "timeseries",
   "description": "MQTT Connect",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [
         "Willow.LiveData.TelemetryStreaming"
        ],
        "operator": "eq"
       },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "TelemetryStreaming-Connect",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Telemetry Streaming - Disconnect",
   "type": "timeseries",
   "description": "MQTT Disconnect",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{FullCustomerInstanceName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [
         "Willow.LiveData.TelemetryStreaming"
        ],
        "operator": "eq"
       },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "TelemetryStreaming-Disconnect",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}