{
 "title": "Log Volume",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AppInsightsInstance",
    "query": "ain-dev-eus,ain-dev-aue,ain-prd-eus2,ain-prd-weu,ain-prd-aue"
   },
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "traces/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Client Request Duration Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "http.client.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Console Logs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ContainerAppConsoleLogs_CL\r\n| summarize Count=count() by bin(TimeGenerated,1m)\r\n| order by TimeGenerated asc\r\n| project TimeGenerated,  Count\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Duration Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Custom Metrics Count By App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| summarize Count=count() by bin(TimeGenerated,1m), AppRoleName\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, AppRoleName, Count\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Custom Metrics Count By Environment/Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| summarize Count=count() by bin(TimeGenerated,1m), Environment, Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Instance, Count\r\n",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.insights/components",
      "dimensionFilters": [
       {
        "dimension": "cloud/roleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}