{
 "title": "MTI Dashboard Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AppInsightsInstance",
    "query": "ain-dev-eus,ain-dev-aue,ain-prd-eus2,ain-prd-weu,ain-prd-aue"
   },
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "FullCustomerInstanceName",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Ingestion Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sites Ingested",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where Name == \"SiteProcessed\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-SiteProcessed",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Buildings Ingested",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where Name == \"Buildings\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Buildings",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twins Ingested by Building",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where Name == \"Twins\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| extend building = Properties.Building\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, building, Sum",
      "resources": [
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Relationships Ingested by Building",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where Name == \"Relationships\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| extend building = Properties.Building\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, building, Sum",
      "resources": [
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  { "title": "Twins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Twin Creates Succeeded",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "Create" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Succeeded" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twin Creates Failed",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "Create" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Failed" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twin Creates Throttled",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "Create" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Throttled" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twin Updates Succeeded",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "Update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Succeeded" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twin Updates Failed",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Failed" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twin Updates Throttled",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Throttled" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Twin Updates Skipped",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Skipped" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "MappingCreate - Succeeded",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 23 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "MappingCreate" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Succeeded" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Mapping Pending - Failed",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 23 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "action", "filters": [ "MappingCreate" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Failed" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Twins",
      "metricNamespace": "microsoft.insights/components",
      "resources": [
       { "metricNamespace": "microsoft.insights/components", "resourceGroup": "$ResourceGroup", "resourceName": "$AppInsightsInstance", "subscription": "$Subscription" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  { "title": "Relationships", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Created/Reset Relationships Succeeded",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Action", "filters": [ "Create" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Succeeded" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Created/Reset Relationships Failed",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 31 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Action", "filters": [ "Create" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Failed" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Created/Reset Relationships Throttled",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 31 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Action", "filters": [ "Create" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Throttled" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Updated Relationships Throttled",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 31 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Action", "filters": [ "update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Throttled" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Updated Relationships Succeeded",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 38 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Action", "filters": [ "update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Succeeded" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Updated Relationships Failed",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 38 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Action", "filters": [ "update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Failed" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Updated Relationships Unchanged",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 38 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Action", "filters": [ "update" ], "operator": "eq" },
       { "dimension": "status", "filters": [ "Skipped" ], "operator": "eq" },
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-Relationships",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}