{
 "title": "MTI Ontology Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AppInsightsInstance",
    "query": "ain-dev-eus,ain-dev-aue,ain-prd-eus2,ain-prd-weu,ain-prd-aue"
   },
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "FullCustomerInstanceName",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Ontology Mapping Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mapping for Input DTMI Not Found",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"MappingForInputDtmiNotFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "Mti-MappingForInputDtmiNotFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Output Mapping For Input Dtmi Not Found",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"OutputMappingForInputDtmiNotFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "Mti-OutputMappingForInputDtmiNotFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Target DTMI Not Found",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"TargetDtmiNotFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-TargetDtmiNotFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Invalid Target DTMIs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"InvalidTargetDtmis\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "FullCustomerInstanceName", "filters": [ "$FullCustomerInstanceName" ], "operator": "eq" }
      ],
      "metricName": "Mti-InvalidTargetDtmis",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "InputInterfaceNotFound not found in Model by InterfaceType",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"InputInterfaceNotFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "Mti-InputInterfaceNotFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Output Mapping For Input Dtmi Not Found",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"OutputMappingForInputDtmiNotFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "Mti-OutputMappingForInputDtmiNotFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Duplicate property found in Model by PropertyName",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"DuplicateMappingPropertyFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "Mti-DuplicateMappingPropertyFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Invalid Output DTMI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"InvalidOutputDtmis\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "Mti-InvalidOutputDtmis",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Relationship Not Found in Model by RelationshipType",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"RelationshipNotFoundInModel\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| extend props = parse_json(Properties)\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, props.RelationshipType, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "RelationshipType",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Mti-RelationshipNotFoundInModel",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Exact Type Not Found",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"ExactTypeNotFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Mti-ExactTypeNotFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Thing Dtmi Not Found",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppMetrics\r\n| where AppRoleName == \"Willow.MappedTopologyIngestion\"\r\n| where Name == \"ThingDtmiNotFound\"\r\n| extend splitted=split(AppRoleInstance, ':')\r\n| extend splitted, Environment = tostring(splitted[0]), Region = tostring(splitted[1]), Stamp = tostring(splitted[2]), Instance = tostring(splitted[3])\r\n| where \"$Environment:csv\" has Environment and \"$Region:csv\" has Region and \"$Stamp:csv\" has Stamp and \"$Instance:csv\" has Instance\r\n| order by TimeGenerated asc\r\n| project TimeGenerated, Environment, Region, Stamp, Instance, Sum",
      "resources": [
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-weu/providers/Microsoft.OperationalInsights/workspaces/logs-prd-weu",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-eus2/providers/Microsoft.OperationalInsights/workspaces/logs-prd-eus2",
       "/subscriptions/fd259995-1de7-4ae8-8431-0d150dcca6f4/resourceGroups/rg-prd-aue/providers/Microsoft.OperationalInsights/workspaces/logs-prd-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-aue/providers/Microsoft.OperationalInsights/workspaces/logs-dev-aue",
       "/subscriptions/48a16780-c719-4528-a0f2-4e7640a9c850/resourceGroups/rg-dev-eus/providers/Microsoft.OperationalInsights/workspaces/logs-dev-eus"
      ]
     },
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "Mti-ThingDtmiNotFound",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}