{
 "title": "Notification Hub",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "NotificationHubName",
    "label": "Notification Hub Name",
    "query": {}
   },
   {
    "name": "NotificationHub",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000
      ],
      "dimensionFilters": [],
      "metricName": "incoming",
      "metricNamespace": "microsoft.notificationhubs/namespaces/notificationhubs",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.NotificationHubs/namespaces/notificationHubs",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$NotificationHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Incoming Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000
      ],
      "dimensionFilters": [],
      "metricName": "incoming.all.failedrequests",
      "metricNamespace": "microsoft.notificationhubs/namespaces/notificationhubs",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.NotificationHubs/namespaces/notificationHubs",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$NotificationHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Successful Notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000
      ],
      "dimensionFilters": [],
      "metricName": "outgoing.allpns.success",
      "metricNamespace": "microsoft.notificationhubs/namespaces/notificationhubs",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.NotificationHubs/namespaces/notificationHubs",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$NotificationHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Outgoing Notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000
      ],
      "dimensionFilters": [],
      "metricName": "notificationhub.pushes",
      "metricNamespace": "microsoft.notificationhubs/namespaces/notificationhubs",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.NotificationHubs/namespaces/notificationHubs",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$NotificationHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Channel Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000
      ],
      "dimensionFilters": [],
      "metricName": "outgoing.allpns.channelerror",
      "metricNamespace": "microsoft.notificationhubs/namespaces/notificationhubs",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.NotificationHubs/namespaces/notificationHubs",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$NotificationHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Payload Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000
      ],
      "dimensionFilters": [],
      "metricName": "outgoing.allpns.invalidpayload",
      "metricNamespace": "microsoft.notificationhubs/namespaces/notificationhubs",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.NotificationHubs/namespaces/notificationHubs",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$NotificationHub",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}