{
 "title": "Search Service",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "SearchService",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Search Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SearchQueriesPerSecond",
      "metricNamespace": "microsoft.search/searchservices",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.search/searchservices",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$SearchService",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SearchLatency",
      "metricNamespace": "microsoft.search/searchservices",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.search/searchservices",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$SearchService",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Skill Execution Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SkillExecutionCount",
      "metricNamespace": "microsoft.search/searchservices",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.search/searchservices",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$SearchService",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Throttled Search Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ThrottledSearchQueriesPercentage",
      "metricNamespace": "microsoft.search/searchservices",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.search/searchservices",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$SearchService",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}