{
 "title": "Service Bus",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "ServiceBusNamespaces",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Messages in Queue/Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Messages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Messages in Queue/Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Messages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Dead Letter Messages in Queue / Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Dead Letter Messages in Queue",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Dead Letter Messages in Queue / Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "DeadletteredMessages",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ActiveConnections",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.servicebus/namespaces",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "Microsoft.ServiceBus/namespaces",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$ServiceBusNamespace",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}