{
 "title": "Willow Applications",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AppInsightsInstance",
    "label": "App Insights Instance",
    "query": "ain-dev-eus,ain-dev-aue,ain-prd-eus2,ain-prd-weu,ain-prd-aue"
   },
   {
    "name": "AllSubscriptions",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Health Checks - Unhealthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "Status", "filters": [ "Unhealthy" ], "operator": "eq" }
      ],
      "metricName": "HealthCheck",
      "metricNamespace": "microsoft.insights/components",
      "region": "East US",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "East US",
        "resourceGroup": "rg-dev-eus",
        "resourceName": "ain-dev-eus",
        "subscription": "48a16780-c719-4528-a0f2-4e7640a9c850"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "48a16780-c719-4528-a0f2-4e7640a9c850"
    }
   ]
  },
  {
   "title": "Health Checks by Application - Unhealthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "Status", "filters": [ "Unhealthy" ], "operator": "eq" }
      ],
      "metricName": "HealthCheck",
      "metricNamespace": "microsoft.insights/components",
      "region": "East US",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "East US",
        "resourceGroup": "rg-dev-eus",
        "resourceName": "ain-dev-eus",
        "subscription": "48a16780-c719-4528-a0f2-4e7640a9c850"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "48a16780-c719-4528-a0f2-4e7640a9c850"
    }
   ]
  },
  {
   "title": "Health Checks by Customer Instance - Unhealthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "CustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "Status", "filters": [ "Unhealthy" ], "operator": "eq" }
      ],
      "metricName": "HealthCheck",
      "metricNamespace": "microsoft.insights/components",
      "region": "East US",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "East US",
        "resourceGroup": "rg-dev-eus",
        "resourceName": "ain-dev-eus",
        "subscription": "48a16780-c719-4528-a0f2-4e7640a9c850"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "48a16780-c719-4528-a0f2-4e7640a9c850"
    }
   ]
  },
  {
   "title": "Availability by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "$Subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M",
      "top": "50"
     },
     "subscription": "$Subscription"
    },
    {
     "downsampler": "last",
     "expression": "TotalRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "downsampler": "min",
     "expression": "FailedRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "expression": "100*($TotalRequestsFilled-$FailedRequestsFilled)/$TotalRequestsFilled",
     "type": "math"
    },
    {
     "downsampler": "last",
     "expression": "Availability",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Availability by App Role Name",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 21 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "$Subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M",
      "top": "50"
     },
     "subscription": "$Subscription"
    },
    {
     "downsampler": "last",
     "expression": "TotalRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "downsampler": "min",
     "expression": "FailedRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "expression": "100*($TotalRequestsFilled-$FailedRequestsFilled)/$TotalRequestsFilled",
     "type": "math"
    },
    {
     "downsampler": "last",
     "expression": "Availability",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Availability by App Role Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 33 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "$Subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M",
      "top": "50"
     },
     "subscription": "$Subscription"
    },
    {
     "downsampler": "last",
     "expression": "TotalRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "downsampler": "min",
     "expression": "FailedRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "expression": "100*($TotalRequestsFilled-$FailedRequestsFilled)/$TotalRequestsFilled",
     "type": "math"
    },
    {
     "downsampler": "last",
     "expression": "Availability",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Failed Requests by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Failed Requests by App Role Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Failed Requests by App Role Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M",
      "top": "50"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Duration by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Duration - By App Role Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Duration - By App Role Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "AppRoleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Counts by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Count - By App Role Name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Count - By App Role Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 58 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "AppRoleName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}