{
 "title": "Willow Single Application Route",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AppInsightsInstance",
    "label": "App Insights Instance",
    "query": "ain-dev-eus,ain-dev-aue,ain-prd-eus2,ain-prd-weu,ain-prd-aue"
   },
   { "name": "AllSubscriptions" },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "Subscription",
    "query": {}
   },
   {
    "name": "Region",
    "query": {}
   },
   {
    "name": "AppName",
    "query": {}
   },
   {
    "name": "Route",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Availability by Customer Instance  - $AppName - $Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       { "dimension": "http.route", "filters": [ "$Route" ], "operator": "eq" },
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       {
        "dimension": "http.route",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto",
      "top": "50"
     },
     "subscription": "$Subscription"
    },
    {
     "downsampler": "last",
     "expression": "TotalRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "downsampler": "min",
     "expression": "FailedRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "expression": "100*($TotalRequestsFilled-$FailedRequestsFilled)/$TotalRequestsFilled",
     "type": "math"
    },
    {
     "downsampler": "last",
     "expression": "Availability",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Availability by App Role Instance - $Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       { "dimension": "http.route", "filters": [ "$Route" ], "operator": "eq" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "$Subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "http.response.status_code", "filters": [ "5" ], "operator": "sw" },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       {
        "dimension": "http.route",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "PT1M",
      "top": "50"
     },
     "subscription": "$Subscription"
    },
    {
     "downsampler": "last",
     "expression": "TotalRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "downsampler": "min",
     "expression": "FailedRequests",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    },
    {
     "expression": "100*($TotalRequestsFilled-$FailedRequestsFilled)/$TotalRequestsFilled",
     "type": "math"
    },
    {
     "downsampler": "last",
     "expression": "Availability",
     "type": "resample",
     "upsampler": "pad",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Server Request Duration by Customer Instance - $Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       { "dimension": "http.route", "filters": [ "$Route" ], "operator": "eq" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Duration - By App Role Instance - $Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       { "dimension": "http.route", "filters": [ "$Route" ], "operator": "eq" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Counts by Customer Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "FullCustomerInstanceName",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       { "dimension": "http.route", "filters": [ "$Route" ], "operator": "eq" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Server Request Count - By App Role Instance - $Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [
       {
        "dimension": "AppRoleInstance",
        "filters": [],
        "operator": "eq"
       },
       { "dimension": "AppRoleName", "filters": [ "$AppName" ], "operator": "eq" },
       { "dimension": "http.route", "filters": [ "$Route" ], "operator": "eq" }
      ],
      "metricName": "http.server.request.duration",
      "metricNamespace": "microsoft.insights/components",
      "region": "$Region",
      "resources": [
       {
        "metricNamespace": "microsoft.insights/components",
        "region": "$Region",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppInsightsInstance",
        "subscription": "$Subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}