managementGroupName: Product
variables:
  identities:
    - &grafana f1dda508-d34e-4234-99ba-917017c14667
    - &Platform_Engineers 28ddc189-5f7c-4a25-9c69-8e5d6830b92c
    - &CognitiveServicesContributor-WillowTwin-Dev c2478702-58a8-4b4a-8c16-5497052495b3
    - &Wilbur a2934358-23ce-4c0b-abaf-2f18d14b6cd6
    - &pipeline-deployer-spn bd2c9873-feb2-4948-88c6-257544aecb64
    - &Azure-WillowTwin-Readers 6a8437c5-2652-4b3b-b88b-4bc1b93592c9
    - &WillowTwin-PlatformEngineers 7a6ce841-907e-41b4-8bed-bef1a489f6f4
    - &dhopper 1a380890-5a41-41b3-ad5c-e280d5f6bb66
  scopes:
    - &managementGroupScope /providers/Microsoft.Management/managementGroups/Product
managementGroupRoles:
  - assignments:
      - *grafana
    scope: *managementGroupScope
    role: Monitoring Reader
  - assignments:
      - *grafana
    scope: *managementGroupScope
    role: Reader
