& "$PSScriptRoot/GenerateGenericAlertRules.ps1"
& "$PSScriptRoot/GenerateAvailabilityByCustomerInstanceAlertRules.ps1"
& "$PSScriptRoot/GenerateAvailabilityByCustomerInstanceAppRoleAlertRules.ps1"
& "$PSScriptRoot/GenerateAvgMemoryWorkingSetAlertRules.ps1"
& "$PSScriptRoot/GenerateDeadLetterMessagesInQueueOrTopicAlertRules.ps1"
& "$PSScriptRoot/GenerateEventHubQueueingAlertRules.ps1"
& "$PSScriptRoot/GenerateServerRequestDurationByCustomerInstanceAppRoleAlertRules.ps1"
& "$PSScriptRoot/GenerateHealthChecksbyCustomerInstanceAlertRules.ps1"
& "$PSScriptRoot/GenerateMTI-InputInterfaceNotFoundAlertRules.ps1"
& "$PSScriptRoot/GenerateMTI-InvalidTargetDtmisAlertRules.ps1"
& "$PSScriptRoot/GenerateMTI-MappingForInputDtmiNotFoundAlertRules.ps1"
& "$PSScriptRoot/GenerateMTI-RelationshipsFailedAlertRules.ps1"
& "$PSScriptRoot/GenerateMTI-TwinsFailedAlertRules.ps1"

