name: Ephemeral-Environment
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of environment to create
        type: string
        required: true
      targetBranchOrTag:
        description: What branch or tag should we try to deploy, will fallback to main>master>newest builds when not found in acr
        default: DEFAULT
        type: string
        required: false
      DestroyEnvironment:
        description: Destroy the environment instead of creating or updating it
        default: false
        type: boolean
        required: false

jobs:
  EphemeralEnvironment:
    uses: WillowInc/AzurePlatform/.github/workflows/Ephemeral-Steps.yml@main
    secrets:
      client_secret: ${{ secrets.CLIENT_SECRET }}
      B2C_CertificatePassword: ${{ secrets.B2C_CertificatePassword }}
    with:
      client_id: ${{ vars.CLIENT_ID }}
      tenant_id: ${{ vars.TENANT_ID_WILLOWINC }}
      subscription_id: ${{ vars.SUBSCRIPTION_ID_K8S_INTERNAL }}
      cluster_resource_group: nonprod-platformapps
      cluster_name: nonprod-platformapps-aks
      name: ${{ inputs.name }}
      targetBranchOrTag: ${{ inputs.targetBranchOrTag }}
      DestroyEnvironment: ${{ inputs.DestroyEnvironment }}
