name: Docs for Pulumi Clusters

on:
  push:
    branches: [main]
    paths:
      - 'SharedClusters/Pulumi/docs/**'
      - 'SharedClusters/Pulumi/mkdocs.yml'
jobs:
  build:
    uses: WillowInc/AzurePlatform/.github/workflows/reusable-workflow-docs-build.yml@main
    secrets:
      jira_password: ${{ secrets.JIRA_PASSWORD }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
      client_id: ${{ secrets.CLIENT_ID }}
      jira_username: ${{ secrets.JIRA_USERNAME }}
    with:
      docs_path: SharedClusters/Pulumi
      backstage_entity_name: 'default/component/pulumi-clusters'
