name: helm-deploy
description: Download and Deploy helm chart artifact
inputs:
  chart_name:
    description: "Name of chart to download"
    required: true
  version:
    description: "Artifact version (semver) to deploy"
    required: false
    default: "0.0.0"
  github_token:
    description: "github token"
    required: true
  namespace:
    description: "K8s namespace to install or upgrade"
    required: true
  name:
    description: "Helm release name"
    required: true
  additional_args:
    description: "Additional argument to pass to install"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download chart
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.chart_name }}-chart
        path: charts/

    - uses: azure/setup-helm@v4
      with:
        version: "latest"
        token: ${{ inputs.github_token }}
      id: install

    - name: Deploy chart
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.namespace }} --namespace ${{ inputs.name }} --create-namespace charts/${{ inputs.chart_name }}-${{ inputs.version }}.tgz ${{ inputs.additional_args }}
