apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kroki.fullname" . }}-app-env
  labels:
    {{- include "kroki.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  KROKI_LISTEN: ':8000'
  KROKI_COMMAND_TIMEOUT: {{ .Values.commandTimeout }}
  KROKI_CONVERT_TIMEOUT: {{ .Values.convertTimeout }}
  {{- range $companion := .Values.companions }}
  KROKI_{{ upper $companion.name }}_HOST:  kroki-{{ $companion.name }}
  KROKI_{{ upper $companion.name }}_PORT:  {{ $companion.port | quote  }}
  {{- end }}
