{
 "title": "Microsoft Azure App Service",
 "description": "Use Azure Monitor to view relevante information of Database",
 "tags": [
  "app service",
  "azure",
  "azure monitor",
  "hosting"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Subscription", "label": "Subscription", "query": "Subscriptions()" },
   { "name": "AppResourceGroup", "label": "App Resource Group", "query": "ResourceGroups($Subscription)" },
   { "name": "AppNamespace", "label": "AppNamespace", "query": "Microsoft.Web/sites" },
   {
    "name": "App",
    "label": "App",
    "query": "ResourceNames($Subscription, $AppResourceGroup,$AppNamespace)"
   },
   { "name": "PlanResourceGroup", "label": "Plan Resource Group", "query": "ResourceGroups($Subscription)" },
   { "name": "PlanNamespace", "label": "PlanNamespace", "query": "Microsoft.Web/serverFarms" },
   {
    "name": "Plan",
    "label": "Plan",
    "query": "ResourceNames($Subscription, $PlanResourceGroup, $PlanNamespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Subscription App Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Apps",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": {
        "query": "Resources\r\n| where type == \"microsoft.web/sites\"\r\n| where  subscriptionId contains \"$Subscription\"\r\n| summarize count()",
        "resultFormat": "table"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
       "subscriptions": [ "$Subscription" ]
      }
     ]
    },
    {
     "title": "Apps",
     "type": "table",
     "gridPos": { "h": 7, "w": 22, "x": 2, "y": 1 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": {
        "query": "Resources\r\n| where type == \"microsoft.web/sites\"\r\n| where  subscriptionId contains \"$Subscription\"\r\n| join kind = leftouter (resourcecontainers | where type == \"microsoft.resources/subscriptions\" | project SubscriptionName=name, subscriptionId) on subscriptionId\r\n| project name, kind, location, resourceGroup, SubscriptionName, webSpace=properties.webSpace, availabilityState=properties.availabilityState, state=properties.state, hostNames=properties.hostNames, sku=properties.sku",
        "resultFormat": "table"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
       "subscriptions": [ "$Subscription" ]
      }
     ]
    },
    {
     "title": "Plans",
     "type": "stat",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": {
        "query": "Resources\r\n| where type contains \"microsoft.web/serverfarms\"\r\n| where  subscriptionId contains \"$Subscription\"\r\n| summarize count()",
        "resultFormat": "table"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
       "subscriptions": [ "$Subscription" ]
      }
     ]
    },
    {
     "title": "Plans",
     "type": "table",
     "gridPos": { "h": 7, "w": 22, "x": 2, "y": 8 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": {
        "query": "Resources\r\n| where type contains \"microsoft.web/serverfarms\"\r\n| where  subscriptionId contains \"$Subscription\"\r\n| join kind = leftouter (resourcecontainers | where type == \"microsoft.resources/subscriptions\" | project SubscriptionName=name, subscriptionId) on subscriptionId\r\n| project name, kind, location, resourceGroup, SubscriptionName, Sku=sku.name, Capacity=sku.capacity ",
        "resultFormat": "table"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
       "subscriptions": [ "$Subscription" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Plan Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Apps On Plan",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where type == \"microsoft.web/sites\"\r\n| extend serverFarmId = tostring(properties.serverFarmId)\r\n| extend serverFarm = extract(\"Microsoft.Web/serverfarms/(.*)\", 1, serverFarmId, typeof(string))\r\n| extend serverFarmResourceGroup = extract(\"resourceGroups/(.*)/providers\", 1, serverFarmId, typeof(string))\r\n| where serverFarmResourceGroup == \"$PlanResourceGroup\" and serverFarm == \"$Plan\"\r\n| summarize count()",
      "resultFormat": "table"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Apps On Plan",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 2 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where type == \"microsoft.web/sites\"\r\n| extend serverFarmId = tostring(properties.serverFarmId)\r\n| extend serverFarm = extract(\"Microsoft.Web/serverfarms/(.*)\", 1, serverFarmId, typeof(string))\r\n| extend serverFarmResourceGroup = extract(\"resourceGroups/(.*)/providers\", 1, serverFarmId, typeof(string))\r\n| where serverFarmResourceGroup == \"$PlanResourceGroup\" and serverFarm == \"$Plan\"\r\n| project Status=properties.state, name, resourceGroup, serverFarm, serverFarmResourceGroup, Hostnames=tostring(properties.enabledHostNames)",
      "resultFormat": "table"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Memory / Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "CpuPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "MemoryPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "DiskQueueLength",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "HttpQueueLength",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "SocketInboundAll",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "SocketOutboundAll",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "SocketOutboundEstablished",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$PlanNamespace",
      "metricName": "SocketOutboundTimeWait",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$PlanResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "App Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "App",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": {
      "query": "resources\r\n| where type == \"microsoft.web/sites\"\r\n| where name == \"$App\"\r\n| extend serverFarmId = tostring(properties.serverFarmId)\r\n| extend serverFarm = extract(\"Microsoft.Web/serverfarms/(.*)\", 1, serverFarmId, typeof(string))\r\n| extend serverFarmResourceGroup = extract(\"resourceGroups/(.*)/providers\", 1, serverFarmId, typeof(string))\r\n| join kind=leftouter (resources| where type == \"microsoft.web/serverfarms\") on $left.serverFarm == $right.name \r\n| project Status=properties.state, Sku=sku1.name, Capacity=sku1.capacity, name, resourceGroup, serverFarm, serverFarmResourceGroup, Hostnames=tostring(properties.enabledHostNames)",
      "resultFormat": "table"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$AppNamespace",
      "metricName": "PrivateBytes",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$AppResourceGroup",
      "resourceName": "$App",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$AppNamespace",
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$AppResourceGroup",
      "resourceName": "$App",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$AppNamespace",
      "metricName": "CpuTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$AppResourceGroup",
      "resourceName": "$App",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$AppNamespace",
      "metricName": "Threads",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$AppResourceGroup",
      "resourceName": "$App",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$AppNamespace",
      "metricName": "Requests",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$AppResourceGroup",
      "resourceName": "$App",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$AppNamespace",
      "metricName": "HttpResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$AppResourceGroup",
      "resourceName": "$App",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "$AppNamespace",
      "metricName": "Http5xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$AppResourceGroup",
      "resourceName": "$App",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  }
 ]
}