{
 "title": "ADT Explorer",
 "description": "Azure Monitor Container Insights",
 "tags": [
  "ADT",
  "Azure"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Subscription", "query": "subscriptions()" },
   {
    "name": "Workspace",
    "query": "/subscriptions/178b67d7-b6fd-46db-b4a3-b57f8a6b045f/resourceGroups/nonprod-platformshared/providers/Microsoft.OperationalInsights/workspaces/nonprodplatformshared-aue-log,/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log,/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log,/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-weu-log"
   },
   { "name": "ResourceGroups", "query": "ResourceGroups($Subscription)" },
   {
    "name": "Type",
    "query": "Microsoft.DigitalTwins/digitalTwinsInstances"
   },
   {
    "name": "ADT",
    "query": "ResourceNames($Subscription, $ResourceGroups,$Type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Twin Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "TwinCount",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Model Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "ModelCount",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "azureMonitor": { "timeGrain": "auto" },
     "azureResourceGraph": {
      "query": "resources\r\n| where type == \"microsoft.digitaltwins/digitaltwinsinstances\" and name == \"$ADT\"\r\n| project location, sku=tostring(sku.name), provisioningState=tostring(properties.provisioningState), created=format_datetime(todatetime(properties.createdTime), 'yyyy-MM-dd hh:mm'), updated=format_datetime(todatetime(properties.lastUpdatedTime), 'yyyy-MM-dd hh:mm'), hostName=tostring(properties.hostName)"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Api Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "ApiRequests",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Api Requests Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "ApiRequestsFailureRate",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Api Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "ApiRequestsLatency",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Avg Response",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "union ADTDigitalTwinsOperation,\r\nADTModelsOperation,\r\nADTQueryOperation\r\n| where _ResourceId contains \"$ADT\"\r\n| where $__timeFilter(TimeGenerated)\r\n| extend Operation = tostring(split(OperationName, 'Microsoft.DigitalTwins/')[1])\r\n| summarize Response=avg(tolong(DurationMs)) by Operation\r\n| order by Response desc",
      "resource": "$Workspace",
      "resultFormat": "time_series"
     },
     "azureMonitor": { "timeGrain": "auto" },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ADTQueryOperation\r\n| where _ResourceId contains \"$ADT\"\r\n| where $__timeFilter(TimeGenerated)\r\n| summarize Response=avg(tolong(DurationMs)), Count=count() by OperationName, TimeGenerated=bin(TimeGenerated, $__interval)\r\n| order by TimeGenerated asc",
      "resource": "$Workspace",
      "resultFormat": "time_series"
     },
     "azureMonitor": { "timeGrain": "auto" },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "union ADTDigitalTwinsOperation,\r\nADTModelsOperation,\r\nADTQueryOperation\r\n| where _ResourceId contains \"$ADT\"\r\n| where $__timeFilter(TimeGenerated)\r\n| extend Operation = tostring(split(OperationName, 'Microsoft.DigitalTwins/')[1])\r\n| summarize Count=count(), Response=avg(tolong(DurationMs)) by Operation\r\n| order by Response desc \r\n| project-away Response",
      "resource": "$Workspace",
      "resultFormat": "time_series"
     },
     "azureMonitor": { "timeGrain": "auto" },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Models Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ADTModelsOperation\r\n| where _ResourceId contains \"$ADT\"\r\n| where $__timeFilter(TimeGenerated)\r\n| summarize Response=avg(tolong(DurationMs)), Count=count() by OperationName, TimeGenerated=bin(TimeGenerated, $__interval)\r\n| order by TimeGenerated asc",
      "resource": "$Workspace",
      "resultFormat": "time_series"
     },
     "azureMonitor": { "timeGrain": "auto" },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Twin Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "ADTDigitalTwinsOperation\r\n| where _ResourceId contains \"$ADT\"\r\n| where $__timeFilter(TimeGenerated)\r\n| summarize Response=avg(tolong(DurationMs)), Count=count() by OperationName, TimeGenerated=bin(TimeGenerated, $__interval)\r\n| order by TimeGenerated asc",
      "resource": "$Workspace",
      "resultFormat": "time_series"
     },
     "azureMonitor": { "timeGrain": "auto" },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Slow Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "union ADTModelsOperation,\r\nADTQueryOperation\r\n| where $__timeFilter(TimeGenerated)\r\n | where _ResourceId contains \"$ADT\"\r\n| summarize TotalDuration=sum(tolong(DurationMs)), Operations=count(), SpanIds=make_set(SpanId), OperationTypes=make_set(Type) by TraceId\r\n| order by TotalDuration desc \r\n| take 5",
      "resource": "$Workspace",
      "resultFormat": "table"
     },
     "azureMonitor": { "timeGrain": "auto" },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ingress Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "dimensionFilters": [],
        "metricDefinition": "$Type",
        "metricName": "IngressEvents",
        "metricNamespace": "$Type",
        "resourceGroup": "$ResourceGroups",
        "resourceName": "$ADT",
        "timeGrain": "auto"
       },
       "subscription": "$Subscription"
      }
     ]
    },
    {
     "title": "Ingress Events Failure Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$Type",
        "metricName": "IngressEventsFailureRate",
        "metricNamespace": "$Type",
        "resourceGroup": "$ResourceGroups",
        "resourceName": "$ADT",
        "timeGrain": "auto"
       },
       "subscription": "$Subscription"
      }
     ]
    },
    {
     "title": "Ingress Events Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "dimensionFilters": [],
        "metricDefinition": "$Type",
        "metricName": "IngressEventsLatency",
        "metricNamespace": "$Type",
        "resourceGroup": "$ResourceGroups",
        "resourceName": "$ADT",
        "timeGrain": "auto"
       },
       "subscription": "$Subscription"
      }
     ]
    }
   ]
  },
  {
   "title": "Billing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Billing Query Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "BillingQueryUnits",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Billing API Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "BillingApiOperations",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Billing Messages Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "BillingMessagesProcessed",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Routing Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Routing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "RoutingLatency",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Routing Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "RoutingFailureRate",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  },
  {
   "title": "Messages Routed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$Type",
      "metricName": "Routing",
      "metricNamespace": "$Type",
      "resourceGroup": "$ResourceGroups",
      "resourceName": "$ADT",
      "timeGrain": "auto"
     },
     "subscription": "$Subscription"
    }
   ]
  }
 ]
}