{
 "title": "ADX Cluster Health",
 "description": "ADX Cluster Resource Usage",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "sub",
    "query": {}
   },
   { "name": "rg", "query": "ResourceGroups($sub)" },
   { "name": "ns", "query": "Microsoft.Kusto/clusters" },
   { "name": "resource", "query": "ResourceNames($sub, $rg, $ns)" },
   {
    "name": "ws",
    "query": "/subscriptions/178b67d7-b6fd-46db-b4a3-b57f8a6b045f/resourceGroups/nonprod-platformshared/providers/Microsoft.OperationalInsights/workspaces/nonprodplatformshared-aue-log,/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log,/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log,/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-weu-log"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# ADX Cluster : ${resource}\r\n[Backstage](https://backstage.devservices.willowinc.com/catalog/default/component/pulumi-clusters)\r\n// [Docs](https://backstage.devservices.willowinc.com/docs/default/component/pulumi-clusters)"
   },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Keep Alive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "KeepAlive",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "CPU",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "CacheUtilization",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "InstanceCount",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "TotalNumberOfConcurrentQueries",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "QueryDuration",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throttle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum",
       "Total"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Command Type", "value": "CommandType" }
      ],
      "metricDefinition": "$ns",
      "metricName": "TotalNumberOfThrottledCommands",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum",
       "Total"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Command Type", "value": "CommandType" }
      ],
      "metricDefinition": "$ns",
      "metricName": "TotalNumberOfThrottledQueries",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Streaming",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "StreamingIngestDataRate",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "StreamingIngestResults",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "StreamingIngestDuration",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "IngestionLatencyInSeconds",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "IngestionVolumeInMB",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Event Hub Events Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "EventStatus",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "EventsProcessedForEventHubs",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Db Discover Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ComponentName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Events By DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "657b3e91-7c0b-438b-86a5-f769445e237d"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       {
        "dimension": "ComponentName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "EventsProcessed",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$sub"
    }
   ]
  }
 ]
}