{
 "title": "Microsoft Azure SQL Database",
 "description": "Use Azure Monitor to view relevante information of Database",
 "tags": [
  "sql",
  "data",
  "azure monitor",
  "azure",
  "database"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Subscriptions", "label": "Subscriptions", "query": "Subscriptions()" },
   { "name": "ResourceGroup", "label": "Resource Group", "query": "ResourceGroups($Subscriptions)" },
   {
    "name": "Namespaces",
    "label": "Namespaces",
    "query": "Namespaces($Subscriptions, $ResourceGroup)"
   },
   {
    "name": "ResourceName",
    "label": "ResourceName",
    "query": "ResourceNames($Subscriptions, $ResourceGroup,$Namespaces)"
   }
  ]
 },
 "panels": [
  {
   "title": "Subscription Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Other Databases",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": {
        "query": "resources\r\n| where type == \"microsoft.sql/servers/databases\"\r\n| where name != \"master\"\r\n| parse id with \"/subscriptions\" sub \"/resourceGroups/\" rg \"/providers/Microsoft.Sql/servers/\" server \"/databases/\" db\r\n| extend dbId = strcat(server, \"/\", db)\r\n| join kind = leftouter (resourcecontainers | where type == \"microsoft.resources/subscriptions\" | project SubscriptionName=name, subscriptionId) on subscriptionId\r\n| project DTU=toint(sku.capacity), Tier=sku.tier, SubscriptionName, DbName=name, resourceGroup, location, dbId\r\n| order by DTU",
        "resultFormat": "table"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
       "subscriptions": [ "$Subscriptions" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Microsoft Azure Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "deadlock",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscriptions",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "DTU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "SPACE %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "2694ae7f-cc15-44ee-84b7-0735c89a9b56"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Maximum",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "storage_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "DATA I/O",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "physical_data_read_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "1"
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "LOG I/O",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "log_write_percent",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "dimensionFilter": "",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "dtu_used",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "dimensionFilter": "",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "dtu_limit",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Maximum",
      "dimensionFilter": "",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "storage",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Maximum",
      "dimensionFilter": "",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "allocated_data_storage",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "DTU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Maximum",
      "alias": "MaxDTU",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscriptions",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "AvgDTU",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscriptions",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Server CPU",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "sqlserver_process_core_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscriptions",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    },
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Server Mem",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "sqlserver_process_memory_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscriptions",
     "subscriptions": [
      "0659c76d-fcbf-4e58-8bce-960b9e0cd100",
      "0be01d84-8432-4558-9aba-ecd204a3ee61",
      "0c69c2fd-b86e-4f3a-9cb6-a72eb9de9902",
      "16c3dd19-5016-4bf8-85e2-8c7e88607b7a",
      "178b67d7-b6fd-46db-b4a3-b57f8a6b045f",
      "1bc38ca0-6f7f-4f68-946f-5359d9ace66a",
      "249312a0-4c83-4d73-b164-18c5e72bf219",
      "2e254e02-1149-4bb8-8db1-f20511afb1a4",
      "3ab44a28-5c8d-4f57-9d5e-b4830331e5db",
      "5b797013-f6dc-4235-a157-e4cb98ef8599",
      "7dab7b5a-d968-43a5-a50f-9509244c297b",
      "89a48b77-62f9-4bc3-8ddc-cd6db25fb0bc",
      "ae0c8612-75e8-4b6e-9443-ce2d7cd35d4e",
      "bdd7479b-ce38-47cf-b22f-285337c1e951",
      "c9a0ae53-c468-4612-a318-cfb719c4b2ca",
      "ca5069fb-5f00-4df3-8491-10ee2768126a",
      "d4746c7a-19cb-47ac-82b5-069b17cb99de",
      "e878a98a-20ec-4516-a59d-f393429fe07c",
      "ee06cff9-d2d7-405a-8ce9-cf82fe78fbf6",
      "f4edc7ff-4396-47be-bf14-90892e463848",
      "f89766c3-f955-42b5-8925-929bd7df83c0"
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "connection_successful",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "connection_failed",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  },
  {
   "title": "Sessions / Workers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "alias": "Workers %",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "workers_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "alias": "Sessions %",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "sessions_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     },
     "subscription": "$Subscriptions"
    }
   ]
  }
 ]
}