{
 "title": "Auth service",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Authz-dev",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/failed",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-authrz-dev-default-40a001a1/providers/Microsoft.Insights/components/ain-twin-authrz-dev-default-dfe7ed9a",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Server Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Authz-dev",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "requests/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-authrz-dev-default-40a001a1/providers/Microsoft.Insights/components/ain-twin-authrz-dev-default-dfe7ed9a",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Number of Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "Authz-dev",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-authrz-dev-default-40a001a1/providers/Microsoft.Insights/components/ain-twin-authrz-dev-default-dfe7ed9a",
      "timeGrain": "auto",
      "top": ""
     }
    }
   ]
  },
  {
   "title": "List of Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\n| where $__timeFilter(timestamp)\n| summarize error_count=count() by problemId",
      "resource": "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-authrz-dev-default-40a001a1/providers/Microsoft.Insights/components/ain-twin-authrz-dev-default-dfe7ed9a",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "HTTP Healthchecks - Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Authz-dev",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "availabilityResults/availabilityPercentage",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-authrz-dev-default-40a001a1/providers/Microsoft.Insights/components/ain-twin-authrz-dev-default-dfe7ed9a",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Send request time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "browserTimings/sendDuration",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-authrz-dev-default-40a001a1/providers/Microsoft.Insights/components/ain-twin-authrz-dev-default-dfe7ed9a",
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}