{
 "title": "Customer Environments",
 "description": "Azure Log Analytics Workspace Usage",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Subscription", "label": "Cluster Subscription", "query": "subscriptions()" },
   { "name": "EnvironmentSubscription", "label": "Environment Subscription", "query": "subscriptions()" },
   { "name": "Workspace", "label": "Log Workspace", "query": "workspaces($Subscription)" },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "AppInsight",
    "query": {}
   },
   {
    "name": "App",
    "query": {}
   },
   {
    "name": "Namespace",
    "query": {}
   },
   {
    "name": "SqlDb",
    "query": {}
   },
   {
    "name": "SqlDbNS",
    "query": "Microsoft.Sql/servers/databases"
   },
   {
    "name": "SbNs",
    "query": "microsoft.servicebus/namespaces"
   },
   {
    "name": "Sb",
    "query": {}
   },
   {
    "name": "StorageNS",
    "query": "microsoft.storage/storageaccounts"
   },
   {
    "name": "Storage",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated)\r\n| extend  AppRoleName = replace_string(AppRoleName, \"-staging\", \"\")\r\n| parse _ResourceId with \"/subscriptions/\" subscriptionId \"/resourcegroups/\" resourcegroups \"/providers/microsoft.insights/components/\" appInsights\r\n| where $__contains(appInsights, $AppInsight)\r\n| where $__contains(AppRoleName, $App) \r\n| where AppRoleName != \"\" and Url != \"\" and Name !startswith \"HEAD \" and Name !startswith \"OPTIONS \" and ResultCode != 404 and ResultCode != \"\" and ResultCode !startswith \"30\" and  Name !in (\"GET /healthcheck\", \"GET /\", \"GET /Error\", \"GET Home/Index\", \"GET /index.html\", \"GET /favicon.ico\")\r\n| extend success_int = case(Success, 1, 0)\r\n| summarize percentiles(DurationMs, 50, 90, 95, 99, 99.9), Success=sum(success_int), Count=count()\r\n| extend Errors=Count-Success, SuccessPercent = round(Success/todouble(Count), 4), P50=percentile_DurationMs_50, P90=percentile_DurationMs_90, P95=percentile_DurationMs_95, P99=percentile_DurationMs_99 , P999=percentile_DurationMs_99_9\r\n| project-away percentile_DurationMs_95, percentile_DurationMs_90, percentile_DurationMs_50, percentile_DurationMs_99, percentile_DurationMs_99_9\r\n| order by Count desc",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated)\r\n| extend  AppRoleName = replace_string(AppRoleName, \"-staging\", \"\")\r\n| parse _ResourceId with \"/subscriptions/\" subscriptionId \"/resourcegroups/\" resourcegroups \"/providers/microsoft.insights/components/\" appInsights\r\n| where $__contains(appInsights, $AppInsight)\r\n| where $__contains(AppRoleName, $App) \r\n| where AppRoleName != \"\" and Url != \"\" and Name !startswith \"HEAD \" and Name !startswith \"OPTIONS \" and ResultCode != 404 and ResultCode != \"\" and ResultCode !startswith \"30\" and  Name !in (\"GET /healthcheck\" \"GET /\" \"GET /Error\" \"GET Home/Index\" \"GET /index.html\" \"GET /favicon.ico\")\r\n| extend success_int = case(Success, 1, 0)\r\n| summarize percentiles(DurationMs, 50, 90, 95, 99), Success=sum(success_int), Count=count() by TimeGenerated=bin(TimeGenerated, $__interval)\r\n| extend Errors=Count-Success, P50=percentile_DurationMs_50, P90=percentile_DurationMs_90, P95=percentile_DurationMs_95, P99=percentile_DurationMs_99\r\n| project-away percentile_DurationMs_95, percentile_DurationMs_90, percentile_DurationMs_50, percentile_DurationMs_99, Count, Errors, Success\r\n| order by TimeGenerated asc ",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "\r\nAppRequests\r\n| extend  AppRoleName = replace_string(AppRoleName, \"-staging\", \"\")\r\n| parse _ResourceId with \"/subscriptions/\" subscriptionId \"/resourcegroups/\" resourcegroups \"/providers/microsoft.insights/components/\" appInsights\r\n| where $__contains(appInsights, $AppInsight)\r\n| where $__contains(AppRoleName, $App) \r\n| where AppRoleName != \"\" \r\n| extend AppVersion = case(AppVersion in (\"1.0.0.1\", \"1.0.0.0\", \"5.0.10\", \"3.1\", \"6.0.3\"), \"\", AppVersion)\r\n| summarize FirstRequest=min(TimeGenerated) by AppVersion, AppRoleName\r\n| where $__timeFilter(FirstRequest)\r\n| extend Release = 1\r\n| order by FirstRequest asc ",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated)\r\n| extend  AppRoleName = replace_string(AppRoleName, \"-staging\", \"\")\r\n| parse _ResourceId with \"/subscriptions/\" subscriptionId \"/resourcegroups/\" resourcegroups \"/providers/microsoft.insights/components/\" appInsights\r\n| where $__contains(appInsights, $AppInsight)\r\n| where $__contains(AppRoleName, $App) \r\n| where AppRoleName != \"\" and Url != \"\" and Name !startswith \"HEAD \" and Name !startswith \"OPTIONS \" and ResultCode != 404 and ResultCode != \"\" and ResultCode !startswith \"30\" and  Name !in (\"GET /healthcheck\" \"GET /\" \"GET /Error\" \"GET Home/Index\" \"GET /index.html\" \"GET /favicon.ico\")\r\n| extend success_int = case(Success, 1, 0)\r\n| summarize Success=sum(success_int), Count=count() by TimeGenerated=bin(TimeGenerated, $__interval)\r\n| extend Errors=Count-Success\r\n| order by TimeGenerated asc ",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "\r\nAppRequests\r\n| extend  AppRoleName = replace_string(AppRoleName, \"-staging\", \"\")\r\n| parse _ResourceId with \"/subscriptions/\" subscriptionId \"/resourcegroups/\" resourcegroups \"/providers/microsoft.insights/components/\" appInsights\r\n| where $__contains(appInsights, $AppInsight)\r\n| where $__contains(AppRoleName, $App) \r\n| where AppRoleName != \"\" \r\n| extend AppVersion = case(AppVersion in (\"1.0.0.1\", \"1.0.0.0\", \"5.0.10\", \"3.1\", \"6.0.3\"), \"\", AppVersion)\r\n| summarize FirstRequest=min(TimeGenerated) by AppVersion, AppRoleName\r\n| where $__timeFilter(FirstRequest)\r\n| extend Release = 1\r\n| order by FirstRequest asc ",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "HTTP/HTTPS Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated)\r\n| extend  AppRoleName = replace_string(AppRoleName, \"-staging\", \"\")\r\n| parse _ResourceId with \"/subscriptions/\" subscriptionId \"/resourcegroups/\" resourcegroups \"/providers/microsoft.insights/components/\" appInsights\r\n| where $__contains(appInsights, $AppInsight)\r\n| where $__contains(AppRoleName, $App) \r\n| where AppRoleName != \"\" and Url != \"\" and Name !startswith \"HEAD \" and Name !startswith \"OPTIONS \" and ResultCode != 404 and ResultCode != \"\" and ResultCode !startswith \"30\" and  Name !in (\"GET /healthcheck\", \"GET /\", \"GET /Error\", \"GET Home/Index\", \"GET /index.html\", \"GET /favicon.ico\")\r\n| extend success_int = case(Success, 1, 0)\r\n| extend AppVersion = case(AppVersion in (\"1.0.0.1\", \"1.0.0.0\", \"5.0.10\", \"3.1\", \"6.0.3\"), \"\", AppVersion)\r\n| summarize Versions=make_set_if(AppVersion, AppVersion != \"\"),  percentiles(DurationMs, 50, 90, 95, 99), Success=sum(success_int), Count=count() by AppRoleName, appInsights\r\n| extend AppInsights=appInsights, Errors=Count-Success, SuccessPercent = round(Success/todouble(Count), 4), P50=percentile_DurationMs_50, P90=percentile_DurationMs_90, P95=percentile_DurationMs_95, P99=percentile_DurationMs_99\r\n| project-away percentile_DurationMs_95, percentile_DurationMs_90, percentile_DurationMs_50, percentile_DurationMs_99,appInsights\r\n| order by Count desc",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Other Requests (Workers and Similar)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "AppRequests\r\n| where $__timeFilter(TimeGenerated)\r\n| extend  AppRoleName = replace_string(AppRoleName, \"-staging\", \"\")\r\n| parse _ResourceId with \"/subscriptions/\" subscriptionId \"/resourcegroups/\" resourcegroups \"/providers/microsoft.insights/components/\" appInsights\r\n| where $__contains(appInsights, $AppInsight)\r\n| where $__contains(AppRoleName, $App) \r\n| where AppRoleName != \"\" and Url == \"\"\r\n| extend success_int = case(Success, 1, 0)\r\n| extend AppVersion = case(AppVersion in (\"1.0.0.1\", \"1.0.0.0\", \"5.0.10\", \"3.1\", \"6.0.3\"), \"\", AppVersion)\r\n| summarize Versions=make_set_if(AppVersion, AppVersion != \"\"),  percentiles(DurationMs, 50, 90, 95, 99), Success=sum(success_int), Count=count() by AppRoleName, appInsights\r\n| extend AppInsights=appInsights, Errors=Count-Success, SuccessPercent = (Success/todouble(Count)) * 100, P50=percentile_DurationMs_50, P90=percentile_DurationMs_90, P95=percentile_DurationMs_95, P99=percentile_DurationMs_99\r\n| project-away percentile_DurationMs_95, percentile_DurationMs_90, percentile_DurationMs_50, percentile_DurationMs_99,appInsights\r\n| order by Count desc",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Deployment Memory Working Set (Avg Per Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"$Namespace\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  {
   "title": "Deployment CPU (Avg Per Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"$Namespace\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'\r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MiliCores=avg((CounterValue / 1000000)) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resource": "$Workspace"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  { "title": "Database $SqlDb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "SqlDb" },
  {
   "title": "$SqlDb Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "dtu_consumption_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$SqlDb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "storage",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$SqlDb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    }
   ]
  },
  {
   "title": "$SqlDb Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "connection_successful",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$SqlDb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "connection_failed",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$SqlDb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Sql/servers/databases",
      "metricName": "blocked_by_firewall",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$SqlDb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    }
   ]
  },
  { "title": "ServiceBus $Sb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "Sb" },
  {
   "title": "Incoming vs Outgoing $Sb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [
       { "dimension": "EntityName", "filter": "", "operator": "eq" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "IncomingMessages",
      "metricNamespace": "Microsoft.ServiceBus/namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Sb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [
       { "dimension": "EntityName", "filter": "", "operator": "eq" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "OutgoingMessages",
      "metricNamespace": "Microsoft.ServiceBus/namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Sb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    }
   ]
  },
  {
   "title": "Connections and Requests $Sb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [
       { "dimension": "", "filter": "", "operator": "eq" }
      ],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ActiveConnections",
      "metricNamespace": "Microsoft.ServiceBus/namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Sb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "SuccessfulRequests",
      "metricNamespace": "Microsoft.ServiceBus/namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Sb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.ServiceBus/namespaces",
      "metricName": "ThrottledRequests",
      "metricNamespace": "Microsoft.ServiceBus/namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Sb",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    }
   ]
  },
  { "title": "Storage $Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }, "repeat": "Storage" },
  {
   "title": "Ingress v Egress $Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Ingress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Storage",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Egress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Storage",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Storage",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    }
   ]
  },
  {
   "title": "Storage $Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessServerLatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Storage",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Storage",
      "timeGrain": "auto"
     },
     "subscription": "$EnvironmentSubscription"
    }
   ]
  }
 ]
}