{
 "title": "Rules Engine Execution Speeds",
 "description": "Shows Rules Engine execution speed, plus other values",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Exceptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exception History - All Customers",
   "type": "heatmap",
   "description": "Use app insights to drill into exception details",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize msft_prod_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-msft-prod-default-98d11ab0/providers/Microsoft.Insights/components/ain-twin-msft-prod-default-50a9cb33"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "msft-prod - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-msft-prod-default-98d11ab0/providers/Microsoft.Insights/components/ain-twin-msft-prod-default-50a9cb33",
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize axa_prod_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-axa-prod-default-532f5232/providers/Microsoft.Insights/components/ain-twin-axa-prod-default-faf0285e"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "axa-prod - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-axa-prod-default-532f5232/providers/Microsoft.Insights/components/ain-twin-axa-prod-default-faf0285e",
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize brf_prod_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-brf-prod-default-3ae022b6/providers/Microsoft.Insights/components/ain-twin-brf-prod-default-aa725391"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "brf-prod - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-brf-prod-default-3ae022b6/providers/Microsoft.Insights/components/ain-twin-brf-prod-default-aa725391",
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize dfw_prod_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-dfw-prod-default-c8a61b3f/providers/Microsoft.Insights/components/ain-twin-dfw-prod-default-b444460a"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "dfw-prod - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-dfw-prod-default-c8a61b3f/providers/Microsoft.Insights/components/ain-twin-dfw-prod-default-b444460a",
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize inv_prod_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-inv-prod-default-5df0fd00/providers/Microsoft.Insights/components/ain-twin-inv-prod-default-a55ad97d"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "inv-prod - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-inv-prod-default-5df0fd00/providers/Microsoft.Insights/components/ain-twin-inv-prod-default-a55ad97d",
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize msft_test_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-msft-test-default-9171831e/providers/Microsoft.Insights/components/ain-twin-msft-test-default-4ea91e40"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "msft-test - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-msft-test-default-9171831e/providers/Microsoft.Insights/components/ain-twin-msft-test-default-4ea91e40",
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize hpk_prod_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-hpk-prod-default-2cc0eb2d/providers/Microsoft.Insights/components/ain-twin-hpk-prod-default-591abd6e"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "hpk-prod - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-hpk-prod-default-2cc0eb2d/providers/Microsoft.Insights/components/ain-twin-hpk-prod-default-591abd6e",
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize bp_prod_count=count() by bin(timestamp, 1h)",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-bp-prod-default-ffa71db3/providers/Microsoft.Insights/components/ain-twin-bp-prod-default-230aa5a9"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "bp-prod - exception-rate",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "exceptions/count",
      "metricNamespace": "microsoft.insights/components",
      "resourceUri": "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-bp-prod-default-ffa71db3/providers/Microsoft.Insights/components/ain-twin-bp-prod-default-230aa5a9",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "List of Exceptions - Select Customer below",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize msft_prod_count=count() by problemId",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-msft-prod-default-98d11ab0/providers/Microsoft.Insights/components/ain-twin-msft-prod-default-50a9cb33"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize axa_prod_count=count() by problemId",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-axa-prod-default-532f5232/providers/Microsoft.Insights/components/ain-twin-axa-prod-default-faf0285e"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize brf_prod_count=count() by problemId",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-brf-prod-default-3ae022b6/providers/Microsoft.Insights/components/ain-twin-brf-prod-default-aa725391"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize dfw_prod_count=count() by problemId",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-dfw-prod-default-c8a61b3f/providers/Microsoft.Insights/components/ain-twin-dfw-prod-default-b444460a"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize inv_prod_count=count() by problemId",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-inv-prod-default-5df0fd00/providers/Microsoft.Insights/components/ain-twin-inv-prod-default-a55ad97d"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize msft_test_count=count() by problemId",
      "resources": [
       "/subscriptions/7dab7b5a-d968-43a5-a50f-9509244c297b/resourceGroups/rg-twin-msft-test-default-9171831e/providers/Microsoft.Insights/components/ain-twin-msft-test-default-4ea91e40"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize hpk_prod_count=count() by problemId",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-hpk-prod-default-2cc0eb2d/providers/Microsoft.Insights/components/ain-twin-hpk-prod-default-591abd6e"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "exceptions\r\n| where $__timeFilter(timestamp) and (cloud_RoleName == \"RulesEngine.Processor\" or cloud_RoleName == \"RulesEngine.Web\")\r\n| summarize bp_prod_count=count() by problemId",
      "resources": [
       "/subscriptions/5f077d49-cd08-48b4-a26b-59d708d7847b/resourceGroups/rg-twin-bp-prod-default-ffa71db3/providers/Microsoft.Insights/components/ain-twin-bp-prod-default-230aa5a9"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "SQL Databases - CPU Utilisation - All Customers",
   "type": "timeseries",
   "description": "Rules Engine SQL Databases - CPU usage",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "sql-twin-msft-prod-default-f4c870c7/RulesEngine"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "sql-twin-axa-prod-default-5cc98dab/RulesEngine"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b",
     "subscriptions": [
      "e878a98a-20ec-4516-a59d-f393429fe07c"
     ]
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "sql-twin-brf-prod-default-4f4e3b9b/RulesEngine"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "sql-twin-dfw-prod-default-c0bf564a/RulesEngine"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "sql-twin-inv-prod-default-9b2a514f/RulesEngine"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "sql-twin-msft-test-default-d3560c4f/RulesEngine"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "sql-twin-hpk-prod-default-a340657c/RulesEngine"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - sql-cpu-usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.Sql/servers/databases",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "sql-twin-bp-prod-default-485e074c/RulesEngine"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "Kubernetes - Deployment CPU Usage Nano Cores Processor - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-axa-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-weu-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-brf-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-dfw-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-inv-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-hpk-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-bp-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/178b67d7-b6fd-46db-b4a3-b57f8a6b045f/resourceGroups/nonprod-platformshared/providers/Microsoft.OperationalInsights/workspaces/nonprodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Kubernetes - Deployment CPU Usage Nano Cores Web - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-axa-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-weu-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-brf-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-dfw-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-inv-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-hpk-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-bp-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'cpuUsageNanoCores'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize CPUusageNanoCores=avg(CounterValue)/10000000 by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/178b67d7-b6fd-46db-b4a3-b57f8a6b045f/resourceGroups/nonprod-platformshared/providers/Microsoft.OperationalInsights/workspaces/nonprodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Kubernetes - Deployment Memory Working Set Processor - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-axa-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-weu-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-brf-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-dfw-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-inv-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-hpk-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-bp-prod\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-processor-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/178b67d7-b6fd-46db-b4a3-b57f8a6b045f/resourceGroups/nonprod-platformshared/providers/Microsoft.OperationalInsights/workspaces/nonprodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Kubernetes - Deployment Memory Working Set Web - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-axa-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-weu-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-brf-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-dfw-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-inv-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-hpk-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-bp-prod\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/d4746c7a-19cb-47ac-82b5-069b17cb99de/resourceGroups/prod-platformshared/providers/Microsoft.OperationalInsights/workspaces/prodplatformshared-eu2-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "subscription": "e878a98a-20ec-4516-a59d-f393429fe07c"
    },
    {
     "azureLogAnalytics": {
      "query": "KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| where Namespace == \"twin-msft-test\" and ServiceName == \"rules-engine-web-svc\"\r\n| summarize arg_max(TimeGenerated, *) by ContainerName\r\n| project Name, ContainerName, ServiceName\r\n| join kind = inner (\r\n    Perf\r\n    | where $__timeFilter(TimeGenerated)\r\n    | where ObjectName == 'K8SContainer'\r\n    | where CounterName == 'memoryWorkingSetBytes'    \r\n    | extend ContainerNameParts = split(InstanceName, '/')\r\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \r\n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \r\n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\r\n    | project TimeGenerated, ContainerName, CounterValue\r\n) on ContainerName\r\n| summarize MemoryWorkingSet=avg(CounterValue) by TimeGenerated=bin(TimeGenerated, $__interval), ServiceName\r\n| order by TimeGenerated asc",
      "resources": [
       "/subscriptions/178b67d7-b6fd-46db-b4a3-b57f8a6b045f/resourceGroups/nonprod-platformshared/providers/Microsoft.OperationalInsights/workspaces/nonprodplatformshared-aue-log"
      ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "ExecutionTotalWaitTime - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - ExecutionTotalWaitTime",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionTotalWaitTime",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "ProportionSpentExecuting - All Customers",
   "type": "timeseries",
   "description": "Where is the time spent?",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b",
     "subscriptions": [
      "e878a98a-20ec-4516-a59d-f393429fe07c"
     ]
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "ADX LineSpeed - All Customers",
   "type": "timeseries",
   "description": "What is the ADX Line Speed?",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b",
     "subscriptions": [
      "e878a98a-20ec-4516-a59d-f393429fe07c"
     ]
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - adx-linespeed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ADXLineSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "Execution Speeds - All Customers",
   "type": "timeseries",
   "description": "How many times faster than real-time?",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - execution-speed",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ExecutionSpeed",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "TimeSeriesTotalValues - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - TimeSeriesTotalValues",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "ProportionSpentInActor - All Customers",
   "type": "timeseries",
   "description": "Where is the time spent?",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b",
     "subscriptions": [
      "e878a98a-20ec-4516-a59d-f393429fe07c"
     ]
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - proportion-spent-in-actor",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentInActor",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - proportion-spent-executing",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ProportionSpentExecuting",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "InsightsGenerated - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - InsightsGenerated",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-InsightsGenerated",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "TimeSeriesTotalPoints - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - TimeSeriesTotalPoints",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-TimeSeriesTotalPoints",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "ActorTotal - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - ActorTotal",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotal",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "MemoryCacheCount - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - MemoryCacheCount",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-MemoryCacheCount",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "ActorTotalCalcValues - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - ActorTotalCalcValues",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalCalculatedValues",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "ActorTotalOutputs - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - ActorTotalOutputs",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-ActorTotalOutputs",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  { "title": "Integration Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "CommandInsightTotalUpsert - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - CommandInsightsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "CommandInsightTotalDeleted - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - CommandInsightsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CommandInsightTotalDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "CalculatedPointsUpsert - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - CalculatedPointsUpsert",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsUpserted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  },
  {
   "title": "CalculatedPointsDeleted - All Customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-prod - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-prod-default-98d11ab0",
        "resourceName": "ain-twin-msft-prod-default-50a9cb33"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "axa-prod - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-axa-prod-default-532f5232",
        "resourceName": "ain-twin-axa-prod-default-faf0285e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "brf-prod - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-brf-prod-default-3ae022b6",
        "resourceName": "ain-twin-brf-prod-default-aa725391"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "dfw-prod - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-dfw-prod-default-c8a61b3f",
        "resourceName": "ain-twin-dfw-prod-default-b444460a"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "inv-prod - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-inv-prod-default-5df0fd00",
        "resourceName": "ain-twin-inv-prod-default-a55ad97d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "msft-test - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-msft-test-default-9171831e",
        "resourceName": "ain-twin-msft-test-default-4ea91e40"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7dab7b5a-d968-43a5-a50f-9509244c297b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "hpk-prod - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-hpk-prod-default-2cc0eb2d",
        "resourceName": "ain-twin-hpk-prod-default-591abd6e"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    },
    {
     "azureLogAnalytics": {
      "query": "customMetrics\r\n| where name == 'RulesEngine-ExecutionSpeed'\r\n| extend HowManyTimesRealTime=(value/valueCount)\r\n| project timestamp, name, HowManyTimesRealTime\r\n| sort by timestamp asc",
      "resources": [ "$Environment$Instance" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "bp-prod - CalculatedPointsDeleted",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "RulesEngine-CalculatedPointsDeleted",
      "metricNamespace": "Microsoft.Insights/components",
      "resources": [
       {
        "resourceGroup": "rg-twin-bp-prod-default-ffa71db3",
        "resourceName": "ain-twin-bp-prod-default-230aa5a9"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "5f077d49-cd08-48b4-a26b-59d708d7847b"
    }
   ]
  }
 ]
}