apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  title: Grafana
  description: Willow Grafana instance
  annotations:
    github.com/project-slug: WillowInc/AzurePlatform
    github.com/team-slug: WillowInc/platform-engineering
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name:=grafana
  tags:
    - tools
    - services
  links:
    - url: https://grafana.devservices.willowinc.com
      title: Site
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: Platform-Engineering
  system: internal-tools
  dependsOn: ['component:pulumi-clusters']
