apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/managed-by: kubectl
    willowinc.com/team: azurePlatform
    willowinc.com/project: willowdev_AzurePlatform_AzurePlatform_Helm.Clusters
spec:
  acme:
    email: willowinc.com@domainsbyproxy.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
