apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: kroki
    app.kubernetes.io/managed-by: kubectl
    willowinc.com/team: azurePlatform
    willowinc.com/project: willowdev_AzurePlatform_AzurePlatform_Kroki
  name: kroki
