replicaCount: 1
appInsightsKey: ''
msAppId: ''
identity:
  name: ''

hostname: ''
keyVaultUri: ''
environment: Production

image:
  repository: nonprodplatformsharedcr.azurecr.io/opsbot-api
  repositoryJob: nonprodplatformsharedcr.azurecr.io/opsbot-worker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: '0.0.70320'

additionalLabels:
  willowinc.com/team: azurePlatform
  willowinc.com/project: willowdev_AzurePlatform_AzurePlatform_OpsBot

job:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  restartPolicy: OnFailure
  schedule: '0 */1 * * *'
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 60Mi
  additionalLabels:
    willowinc.com/team: azurePlatform
    willowinc.com/project: willowdev_AzurePlatform_AzurePlatform_OpsBot

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    privileged: false
    allowPrivilegeEscalation: false

  nodeSelector: {}

  tolerations: []

  affinity: {}

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  privileged: false
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: opsbot.devservices.willowinc.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: opsbot-tls
      hosts:
        - opsbot.devservices.willowinc.com

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
