msAppId: 'dc4be044-3b3f-4add-a8f3-d89741ee4c89'
appInsightsKey: '39e0ce0f-150f-422e-909d-fbabe809672a'
environment: Development
hostname: https://opsbot-dev.devservices.willowinc.com
identity:
  name: 'ops-bot-dev-id'

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: opsbot-dev.devservices.willowinc.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: opsbot-dev-tls
      hosts:
        - opsbot-dev.devservices.willowinc.com
