apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: customer-auth-gateway-upstream
  namespace: cluster-gloo
  labels:
    app.kubernetes.io/managed-by: kubectl
    willowinc.com/team: twinPlatform
    app.kubernetes.io/name: customer-auth-gateway-upstream
spec:
  kube:
    selector:
      app: customer-auth-gateway
    serviceName: customer-auth-gateway-svc
    serviceNamespace: twin-shared-prod-australiaeast
    servicePort: 80
---
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: cluster-gloo
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      healthCheck:
        path: /healthz

