{
 "title": "AXA - Portfolio View",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostMemPercentThreshold", "query": "80" },
   { "name": "hostCpuPercentThreshold", "query": "80" },
   { "name": "hostDiskPercentThreshold", "query": "90" },
   { "name": "localMessagesSentThreshold", "query": "0" },
   { "name": "upstreamMessagesSentThreshold", "query": "0" },
   { "name": "firstPanicNoDataThresholdMins", "query": "30" },
   { "name": "secondPanicNoDataThresholdMins", "query": "120" },
   { "name": "qlenThreshold", "query": "100" },
   { "name": "customerName", "query": "AXA" }
  ]
 },
 "panels": [
  { "title": "Edge Device  Connectivity ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "datatable(name:string)\r\n[\r\n '$customerName'\r\n]",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-axa-weu2-app-rsg/providers/Microsoft.Devices/IotHubs/wil-prd-lda-axa-weu2-iot"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "Unified Monitoring IoT Edge device and modules, amount of RAM and percent of CPU used on the device. ",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "//Site level status \r\n\r\n// Set thresholds based on workbook parameter values.\r\nlet hostMemPercentThreshold = toint($hostMemPercentThreshold); // 80;\r\nlet hostCpuPercentThreshold = toint($hostCpuPercentThreshold); // 80;\r\nlet hostDiskPercentThreshold = toint($hostDiskPercentThreshold); // 90;\r\nlet localMessagesSentThreshold = toint($localMessagesSentThreshold); // 0;\r\nlet upstreamMessagesSentThreshold = toint($upstreamMessagesSentThreshold); // 0;\r\nlet qlenThreshold = toint($qlenThreshold); // 100;\r\nlet firstPanicNoDataThresholdMins = toint($firstPanicNoDataThresholdMins); // 30;\r\nlet secondPanicNoDataThresholdMins = max_of(firstPanicNoDataThresholdMins, toint($secondPanicNoDataThresholdMins)); // 120;\r\nlet startTime = todatetime('${__from:date}');\r\nlet endTime =  todatetime('${__to:date}');\r\n\r\n//query\r\nlet _data = InsightsMetrics\r\n    | where TimeGenerated between (startTime .. endTime) // restrict the time window\r\n    | extend iotresource = split(_ResourceId, \"/\")[-1]\r\n    | extend device = strcat(iotresource, \"/\", extract(\"edge_device.:.([^,]+).,\", 1, Tags, typeof(string)));\r\nlet cpu_percent = _data\r\n    | where Name == \"edgeAgent_used_cpu_percent\" and Tags contains_cs \"host\" and Tags contains_cs \"0.99\"\r\n    | extend value = toint(Val)\r\n    | top-nested of device by Ignore0=max(1),\r\n      top-nested 3 of TimeGenerated by Ignore1=max(TimeGenerated),\r\n      top-nested of value by Ignore2=max(1)\r\n    | project-away Ignore*\r\n    | summarize p95HostCpu=max(value) by device;\r\n//\r\nlet totalMemByDevice = _data\r\n    | where Name == \"edgeAgent_total_memory_bytes\" and Tags contains_cs \"host\"\r\n    | extend value = tolong(Val)\r\n    | project device, value, TimeGenerated\r\n    | top-nested of device by Ignore0=max(1),\r\n      top-nested 3 of TimeGenerated by Ignore1=max(TimeGenerated),\r\n      top-nested of value by Ignore2=max(1)\r\n    | project-away Ignore*\r\n    | summarize total_bytes=max(value) by device;\r\n//\r\nlet memUsedPercent = _data\r\n    | where Name == \"edgeAgent_used_memory_bytes\" and Tags contains_cs \"host\"\r\n    | top-nested of device by Ignore0=max(1),\r\n      top-nested 3 of TimeGenerated by Ignore1=max(TimeGenerated),\r\n      top-nested of Val by Ignore2=max(1)\r\n    | project-away Ignore*\r\n    | extend used_bytes = tolong(Val) \r\n    | project device, used_bytes, TimeGenerated\r\n    | join kind=leftouter totalMemByDevice on $left.device == $right.device\r\n    | extend mem_used_percent = (todouble(used_bytes) / todouble(total_bytes)) * 100\r\n    | extend mem_used_percent = round(mem_used_percent, 0)\r\n    | summarize p95HostMem=max(mem_used_percent) by device;\r\n//\r\nlet cpu_and_mem = memUsedPercent\r\n    | join cpu_percent on $left.device == $right.device\r\n    | project-away device1;\r\n//\r\nlet totalBytesByDevice = _data\r\n    | where Name == \"edgeAgent_total_disk_space_bytes\"\r\n    | extend dimensions=parse_json(Tags)\r\n    | extend value = tolong(Val)\r\n    | extend diskname = tostring(dimensions.disk_name)\r\n    | extend diskfs = tostring(dimensions.disk_filesystem)\r\n    | where diskfs != \"overlay\"\r\n    | top-nested of device by Ignore0=max(1),\r\n      top-nested 3 of TimeGenerated by Ignore1=max(TimeGenerated),\r\n      top-nested of value by Ignore2=max(1),\r\n      top-nested of diskname by Ignore3=max(1)\r\n    | project-away Ignore*\r\n    | project device, diskname, value, TimeGenerated\r\n    | summarize Bytes=max(value) by device, diskname\r\n    | summarize totalBytes=sum(Bytes) by device;\r\n//\r\nlet used_disk_trend = _data\r\n    | where Name == \"edgeAgent_available_disk_space_bytes\"\r\n    | extend dimensions=parse_json(Tags)\r\n    | extend value = tolong(Val)\r\n    | extend diskname = tostring(dimensions.disk_name)\r\n    | extend diskfs = tostring(dimensions.disk_filesystem)\r\n    | where diskfs != \"overlay\"\r\n    | top-nested of device by Ignore0=max(1),\r\n      top-nested 3 of TimeGenerated by Ignore1=max(TimeGenerated),\r\n      top-nested of value by Ignore2=max(1),\r\n      top-nested of diskname by Ignore3=max(1)\r\n    | project-away Ignore*\r\n    | project device, diskname, value, TimeGenerated\r\n    | summarize Bytes=max(value) by device, diskname, TimeGenerated\r\n    | summarize availBytes=sum(Bytes) by device, TimeGenerated\r\n    | join kind=leftouter\r\n        totalBytesByDevice\r\n        on $left.device == $right.device\r\n    | extend percentUsed = round((todouble(totalBytes) - todouble(availBytes)) / todouble(totalBytes) * 100, 0)\r\n    | project TimeGenerated, device, percentUsed\r\n    | summarize p95Disk=max(percentUsed) by device;\r\n//\r\nlet cpu_mem_disk = cpu_and_mem\r\n    | join\r\n        used_disk_trend\r\n        on $left.device == $right.device\r\n    | project-away device1;\r\n//\r\nlet p95QlenByDevice = _data\r\n    | where Name == \"edgehub_queue_length\"\r\n    | extend dimensions=parse_json(Tags)\r\n    | extend ep = tostring(dimensions.endpoint)\r\n    | extend qlen = iif(Val > 0x7FFFFFFFFFFFFFFF, toreal(0), Val)\r\n    | top-nested of device by Ignore0=max(1),\r\n      top-nested 3 of TimeGenerated by Ignore1=max(TimeGenerated),\r\n      top-nested of qlen by Ignore2=max(1),\r\n      top-nested of ep by Ignore3=max(1)\r\n    | project-away Ignore*\r\n    | project device, qlen, ep, TimeGenerated\r\n    | summarize sum(qlen) by TimeGenerated, device\r\n    | summarize p95QLen = max_of(0, max(sum_qlen)) by device;\r\n//\r\nlet lastUpdateTimeByDevice = _data\r\n    | where Name == \"edgehub_gettwin_total\" or Name == \"edgeAgent_total_time_running_correctly_seconds\"\r\n    | project TimeGenerated, device\r\n    | summarize lastUpdateTime=max(TimeGenerated) by device;\r\n//\r\nlet p95QlenByDeviceAndLastUpdate = p95QlenByDevice \r\n    | join kind=rightouter lastUpdateTimeByDevice on device\r\n    | extend device=device1\r\n    | project-away device1\r\n    | extend lastUpdatedSeconds = tolong(datetime_diff('second', now(), lastUpdateTime))\r\n    | extend lastUpdatedMins = tolong(datetime_diff('minute', now(), lastUpdateTime))\r\n    | extend lastUpdatedHours = tolong(datetime_diff('hour', now(), lastUpdateTime))\r\n    | extend lastUpdatedDays = tolong(datetime_diff('day', now(), lastUpdateTime))\r\n    | extend agoText = case(lastUpdatedSeconds <= 60, strcat(\"seen \", lastUpdatedSeconds, iff(lastUpdatedSeconds == 1, \" sec ago\", \" secs ago\")),\r\n        lastUpdatedSeconds <= 3600, strcat(\"seen \", lastUpdatedMins, iff(lastUpdatedMins == 1, \" min ago\", \" mins ago\")), \r\n        lastUpdatedSeconds <= 86400, strcat(\"seen \", lastUpdatedHours, iff(lastUpdatedHours == 1, \" hr ago\", \" hrs ago\")),\r\n        strcat(\"👀 \", lastUpdatedDays, iff(lastUpdatedDays > 1, \" days ago\", \" day ago\")))\r\n    | project agoText, device, p95QLen, lastUpdatedMins;\r\n//\r\nlet qlenAndLastUpdate = p95QlenByDeviceAndLastUpdate\r\n    | join kind=leftouter\r\n        cpu_mem_disk\r\n        on $left.device == $right.device\r\n    | project-away device1;\r\n// Local and upstream messages\r\nlet recentMessageCount = _data\r\n    | where Name == \"edgehub_messages_sent_total\"\r\n    | project TimeGenerated, device, Val, Tags\r\n    | partition hint.strategy=native by device (\r\n        sort by device, TimeGenerated desc \r\n        | extend target = trim_start(@\"[^/]+/\", extract(\"to.:.([^,]+).,\", 1, Tags, typeof(string))) // using extract which is faster than extractjson\r\n        | extend isupstream = target has \"Upstream\"\r\n        | extend source = strcat(device, \"::\", trim_start(@\"[^/]+/\", extract(\"from.:.([^,]+).,\", 1, Tags, typeof(string))))\r\n        | extend sourceTarget = strcat(source, \"::\", target)\r\n        | summarize msgCounts = make_list(Val)\r\n                 by device, source, sourceTarget, isupstream\r\n    )\r\n    | extend diffs = series_subtract(msgCounts, array_shift_left(msgCounts, 1, toint(msgCounts[-1]))), zeroes = repeat(0, array_length(msgCounts))\r\n    | extend diffs = array_iff(series_greater(diffs, zeroes), diffs, zeroes)\r\n    | extend latestDiff = max_of(toint(diffs[0]), 0)\r\n    | summarize recentUpstreamMessages = sumif(latestDiff, isupstream),\r\n                totalUpstreamMessages = sumif(array_sum(diffs), isupstream),\r\n                recentLocalMessages = sumif(latestDiff, not(isupstream)),\r\n                totalLocalMessages = sumif(array_sum(diffs), not(isupstream))\r\n             by device;\r\n// Final join\r\nqlenAndLastUpdate\r\n| join kind=leftouter recentMessageCount \r\n    on device\r\n| project-away device1\r\n| extend healthIndicator = \r\n    iff((p95HostMem < hostMemPercentThreshold \r\n        and p95HostCpu < hostCpuPercentThreshold \r\n        and p95Disk < hostDiskPercentThreshold \r\n        and p95QLen < qlenThreshold),\r\n        iff(lastUpdatedMins < firstPanicNoDataThresholdMins, 0, 1),\r\n        2\r\n    )\r\n| extend healthIndicator = \r\n    iff(lastUpdatedMins > secondPanicNoDataThresholdMins,\r\n        1,\r\n        iff((isnull(p95HostMem) or p95HostMem < hostMemPercentThreshold) \r\n            and (isnull(p95HostCpu) or p95HostCpu < hostCpuPercentThreshold)\r\n            and (isnull(p95Disk) or p95Disk < hostDiskPercentThreshold)\r\n            and (isnull(p95QLen) or p95QLen < qlenThreshold) \r\n            and (recentLocalMessages >= localMessagesSentThreshold or localMessagesSentThreshold == 0)\r\n            and (recentUpstreamMessages >= upstreamMessagesSentThreshold or upstreamMessagesSentThreshold == 0),\r\n            0,\r\n            2\r\n        )\r\n    )\r\n| extend statusHelper = \r\n    case(\r\n        lastUpdatedMins > secondPanicNoDataThresholdMins, -2,\r\n        lastUpdatedMins > firstPanicNoDataThresholdMins, -1,\r\n        healthIndicator\r\n    )\r\n| extend healthText = \r\n    case(\r\n        statusHelper == 0, \"Healthy\",\r\n        statusHelper == 1, \"Unhealthy\",\r\n        statusHelper == 2, \"Unhealthy\",\r\n        \"Unknown\"\r\n    )\r\n| extend iotresource_device = split(device, \"/\")\r\n| extend iotresource = tostring(iotresource_device[0])\r\n| extend device = tostring(iotresource_device[1])\r\n| extend resourceIndex = array_index_of(split(\"{IoTResources:name}\", \", \"), iotresource)\r\n| extend iotResourceId = trim(\"'\", tostring(split(\"{IoTResources}\", \",\")[resourceIndex]))\r\n| project iotresource, device, healthText, agoText,  p95HostCpu= strcat(p95HostCpu,'%'), p95HostMem=strcat(p95HostMem,'%'), p95Disk=strcat(p95Disk,'%') //, totalLocalMessages, totalUpstreamMessages\r\n| order by p95HostCpu desc, p95HostMem desc, p95Disk desc, device asc;\r\n",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-axa-weu2-app-rsg/providers/Microsoft.Devices/IotHubs/wil-prd-lda-axa-weu2-iot"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "let startTime = '${__from:date}';\r\nlet endTime = '${__to:date}';\r\n\r\ncustomEvents\r\n| where timestamp between (todatetime(startTime) .. todatetime(endTime))\r\n| where name has \"PartialOutageAlert\" \r\n| extend dimensions=parse_json(customDimensions)\r\n| extend metrics=parse_json(customMeasurements)\r\n| extend customer = tostring(dimensions.CustomerName)\r\n| extend connectorName = tostring(dimensions.ConnectorName)\r\n| extend siteName = tostring(dimensions.SiteName)\r\n| extend thirdPartyConsumers = tostring(dimensions.ThirdPartyConsumers)\r\n| extend connectorType = strcat(trim_start('Default',tostring(dimensions.ConnectorType)),\"Module\")\r\n| extend activeCapability = tostring(metrics.ActiveCapabilities)\r\n| extend TrendingCapabilities = tostring(metrics.TrendingCapabilities)\r\n| extend ActualPercentage = tostring(dimensions.['Actual%'])\r\n| extend MinimumPercentage = tostring(dimensions.['Minimum%'])\r\n| extend DegradedTrendingCapabilitiesAdxAlert = tostring(metrics.DegradedTrendingCapabilitiesAdxAlert)\r\n| extend module=strcat(connectorName,\"-\",connectorType) \r\n| extend device = tostring(dimensions.DeviceName)\r\n| extend device = iff(device == '', connectorName, device)\r\n| where customer =~ '$customerName'\r\n| summarize count = count() by device\r\n| project device, partialOutageStatus = 'Unhealthy'\r\n",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-weu2-app-rsg/providers/Microsoft.Insights/components/wil-prd-lda-weu2-ain"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "let startTime = '${__from:date}';\r\nlet endTime = '${__to:date}';\r\n\r\ncustomEvents\r\n| where timestamp between (todatetime(startTime) .. todatetime(endTime))\r\n| where name has \"FullOutageAlert\"\r\n| extend dimensions=parse_json(customDimensions)\r\n| extend metrics=parse_json(customMeasurements)\r\n| extend customer = tostring(dimensions.CustomerName)\r\n| extend connectorName = tostring(dimensions.ConnectorName)\r\n| extend thirdPartyConsumers = tostring(dimensions.ThirdPartyConsumers)\r\n| extend device = tostring(dimensions.DeviceName)\r\n| extend device = iff(device == '', connectorName, device)\r\n| extend siteName = tostring(dimensions.SiteName)\r\n| where customer =~ '$customerName'\r\n| summarize count = count() by device\r\n| project device, fullOutageStatus = 'Unhealthy'",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-weu2-app-rsg/providers/Microsoft.Insights/components/wil-prd-lda-weu2-ain"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "\r\n//Set thresholds based on workbook parameter values.\r\nlet hostMemPercentThreshold = toint($hostMemPercentThreshold); // 80;\r\nlet hostCpuPercentThreshold = toint($hostCpuPercentThreshold); // 80;\r\nlet hostDiskPercentThreshold = toint($hostDiskPercentThreshold); // 90;\r\nlet firstPanicNoDataThresholdMins = toint($firstPanicNoDataThresholdMins); // 30;\r\nlet secondPanicNoDataThresholdMins = max_of(firstPanicNoDataThresholdMins, toint($secondPanicNoDataThresholdMins)); // 120;\r\nlet startTime = todatetime('${__from:date}');\r\nlet endTime =  todatetime('${__to:date}');\r\n\r\ncustomEvents\r\n| where timestamp between (startTime .. endTime)\r\n| where name == 'CustomDeviceMetrics'\r\n| where customDimensions.IsWindowsVm == true\r\n| where isnotnull(customMeasurements.SystemMemoryTotal)\r\n| extend Connector = tostring(customDimensions.ConnectorName)\r\n| where isnotnull(customMeasurements.SystemMemoryTotal)\r\n| extend SystemMemoryTotal = customMeasurements.SystemMemoryTotal\r\n| extend SystemMemoryUsage = customMeasurements.SystemMemoryUsage\r\n| extend SystemCpuUsage = customMeasurements.SystemCpuUsage\r\n| extend SystemDiskUsagePercent = customMeasurements.SystemDiskUsagePercent\r\n| extend SystemMemoryPercentage = toint(todouble(SystemMemoryUsage)/todouble(SystemMemoryTotal) * 100)\r\n| summarize \r\n    p95CPU = percentile(toint(SystemCpuUsage), 95), \r\n    p95Memory = percentile(toint(SystemMemoryPercentage), 95), \r\n    p95Disk = percentile(toint(SystemDiskUsagePercent), 95),\r\n    LastSeenTime = now() - max(timestamp)\r\n    by Connector\r\n| extend lastUpdatedMins = toint(LastSeenTime/ 1m)\r\n| extend healthIndicator = \r\n    iff((p95Memory < hostMemPercentThreshold \r\n        and p95CPU < hostCpuPercentThreshold\r\n        and p95Disk < hostDiskPercentThreshold),\r\n        iff(lastUpdatedMins < firstPanicNoDataThresholdMins, 0, 1),\r\n        2\r\n    )\r\n| extend healthIndicator = \r\n    iff(lastUpdatedMins > secondPanicNoDataThresholdMins,\r\n        1,\r\n        iff((isnull(p95Memory) or p95Memory < hostMemPercentThreshold) \r\n            and (isnull(p95CPU) or p95CPU < hostCpuPercentThreshold)\r\n            and (isnull(p95Disk) or p95Disk  < hostDiskPercentThreshold),\r\n            0,\r\n            2\r\n        )\r\n    )\r\n| extend LastSeen = case(\r\n        LastSeenTime < 1m, strcat(toint(LastSeenTime/1s), \" seconds ago\"),\r\n        LastSeenTime < 2h, strcat(toint(LastSeenTime/1m), \" min ago\"),\r\n        LastSeenTime < 2d, strcat(toint(LastSeenTime/1h), \" hours ago\"),\r\n        LastSeenTime < 14d, strcat(toint(LastSeenTime/1d), \" days ago\"),\r\n        strcat(toint(LastSeenTime/7d), \" weeks ago\")\r\n    )\r\n| extend Status = iff(healthIndicator == 0, 'Healthy', 'Unhealthy'), iotresource = 'Windows VM'\r\n| project iotresource, device = Connector, healthText = Status, agoText = strcat('seen ', LastSeen), p95HostCpu = strcat(p95CPU, '%'), p95HostMem = strcat(p95Memory, '%'), p95Disk = strcat(p95Disk, '%')",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-axa-weu2-app-rsg/providers/Microsoft.Insights/components/wil-prd-lda-axa-weu2-ain"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Healthy Devices",
   "type": "stat",
   "description": "Monitor resource usage.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  {
   "title": "Unhealthy Devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 15 }
   ]
  },
  { "title": "Device Telemetry ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Telemetry Messages Sent",
   "type": "timeseries",
   "description": " device-to-cloud telemetry messages sent successfully to your IoT hub",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "d2c.telemetry.ingress.success",
      "metricNamespace": "microsoft.devices/iothubs",
      "resourceUri": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-axa-weu2-app-rsg/providers/Microsoft.Devices/IotHubs/wil-prd-lda-axa-weu2-iot",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Data Delivered to Storage",
   "type": "timeseries",
   "description": "The amount of data  IoT Hub delivered to storage endpoints.",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 12 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "d2c.endpoints.egress.storage.bytes",
      "metricNamespace": "microsoft.devices/iothubs",
      "resourceUri": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-axa-weu2-app-rsg/providers/Microsoft.Devices/IotHubs/wil-prd-lda-axa-weu2-iot",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "All Connectors",
   "type": "table",
   "description": "List of connector deployed ",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "InsightsMetrics \r\n| extend dimensions=parse_json(Tags) \r\n| extend device = tostring(dimensions.edge_device)\r\n| where Name  == 'edgehub_messages_received_total'\r\n| extend source = trim_start(@\"[^/]+/\", tostring(dimensions.id))\r\n| where not (source has_any(\"host\", \"MetricsCollectorModule\", \"edgeAgent\",\"edgeHub\"))\r\n| summarize by device,source = replace_regex(source,'-([A-Za-z0-9]*)ConnectorModule$','')\r\n| summarize sources = strcat_array(make_list(source), \" | \") by device\r\n| order by device\r\n\r\n \r\n\r\n//  InsightsMetrics \r\n//  | summarize  by Name",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-axa-weu2-app-rsg/providers/Microsoft.Devices/IotHubs/wil-prd-lda-axa-weu2-iot",
      "resultFormat": "table"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    },
    {
     "azureLogAnalytics": {
      "query": "customEvents\r\n| where name == 'CustomDeviceMetrics'\r\n| where customDimensions.IsWindowsVm == true\r\n| where isnotnull(customMeasurements.SystemMemoryTotal)\r\n| extend sources = tostring(customDimensions.ConnectorName)\r\n| distinct sources\r\n| extend device = ''\r\n| project sources, device",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-axa-weu2-app-rsg/providers/Microsoft.Insights/components/wil-prd-lda-axa-weu2-ain"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  { "title": "Connector Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Full Outages",
   "type": "table",
   "description": "Outages when no new telemetry is ingested within the last 30 minutes",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let startTime = '${__from:date}';\r\nlet endTime = '${__to:date}';\r\ncustomEvents\r\n| where timestamp between (todatetime(startTime) .. todatetime(endTime))\r\n| where name has \"FullOutageAlert\"\r\n| extend dimensions=parse_json(customDimensions)\r\n| extend metrics=parse_json(customMeasurements)\r\n| extend customer = tostring(dimensions.CustomerName)\r\n| extend connectorName = tostring(dimensions.ConnectorName)\r\n| extend thirdPartyConsumers = tostring(dimensions.ThirdPartyConsumers)\r\n| where customer =~ '$customerName'\r\n| project timestamp, name, connectorName, thirdPartyConsumers\r\n| order by timestamp desc",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-weu2-app-rsg/providers/Microsoft.Insights/components/wil-prd-lda-weu2-ain"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Partial Outages",
   "type": "table",
   "description": "Outages when telemetry ingested is less than expected.",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let startTime = '${__from:date}';\r\nlet endTime = '${__to:date}';\r\n\r\ncustomEvents\r\n| where timestamp between (todatetime(startTime) .. todatetime(endTime))\r\n| where name has \"PartialOutageAlert\" \r\n| extend dimensions=parse_json(customDimensions)\r\n| extend metrics=parse_json(customMeasurements)\r\n| extend customer = tostring(dimensions.CustomerName)\r\n| extend connectorName = tostring(dimensions.ConnectorName)\r\n| extend thirdPartyConsumers = tostring(dimensions.ThirdPartyConsumers)\r\n| extend connectorType = strcat(trim_start('Default',tostring(dimensions.ConnectorType)),\"Module\")\r\n| extend activeCapability = tostring(metrics.ActiveCapabilities)\r\n| extend TrendingCapabilities = tostring(metrics.TrendingCapabilities)\r\n| extend ActualPercentage = tostring(dimensions.['Actual%'])\r\n| extend MinimumPercentage = tostring(dimensions.['Minimum%'])\r\n| extend DegradedTrendingCapabilitiesAdxAlert = tostring(metrics.DegradedTrendingCapabilitiesAdxAlert)\r\n| extend module=strcat(connectorName,\"-\",connectorType) \r\n| where customer =~ '$customerName'\r\n| project timestamp, name, connectorName, thirdPartyConsumers, module, activeCapability, TrendingCapabilities, ActualPercentage, MinimumPercentage, DegradedTrendingCapabilitiesAdxAlert\r\n| order by timestamp desc\r\n\r\n",
      "resource": "/subscriptions/e878a98a-20ec-4516-a59d-f393429fe07c/resourceGroups/t3-wil-prd-lda-weu2-app-rsg/providers/Microsoft.Insights/components/wil-prd-lda-weu2-ain"
     },
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  }
 ]
}