name: AMG-Grafana-Alerts-Regeneration

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: write

jobs:
  Alert-Regeneration:
    environment: NonProd
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show Existing alert files
        run: tree -F Grafana/alerts/AlertRules

      - uses: actions/setup-node@v4
        name: Install Node 20
        with:
          node-version: 20

      - name: OIDC Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID_WILLOWINC }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID_DEV }}

      - name: Regenerate All Alerts
        shell: pwsh
        run: |
          install-module -Name psyml -Force -SkipPublisherCheck
          ./Grafana/alerts/GenerateAllAlertRules.ps1

      - run: npm ci

      - name: Run Prettier
        run: yarn prettier --write Grafana/alerts/AlertRules *.json

      - name: Git status
        run: git status

      - name: Stage alerts
        run: git add Grafana/alerts/AlertRules

      - name: Commit alerts
        run: |
          git config user.email "githubsvc@willowinc.com"
          git config user.name "githubsvc"
          git checkout -b grafanaAlerts
          git commit -m "Regenerate all alerts" -m "This commit was generated by the AMG-Grafana-Alerts-Regeneration workflow." --no-verify

      - name: Push alerts
        run: git push -f --set-upstream origin +grafanaAlerts

      - name: Create PR
        run: gh pr create --title "Updating alert rules" --body "Updating alert rules" --base "main"
        env:
            GH_TOKEN: ${{ github.token }}
