name: Docs for AzurePlatform Team

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "mkdocs.yml"
jobs:
  build:
    uses: WillowInc/AzurePlatform/.github/workflows/reusable-workflow-docs-build.yml@main
    secrets:
      jira_password: ${{ secrets.JIRA_PASSWORD }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
      client_id: ${{ secrets.CLIENT_ID }}
      jira_username: ${{ secrets.JIRA_USERNAME }}
    with:
      backstage_entity_name: "default/component/platform-docs"
