# .github/workflows/stale-branches.yml

name: Stale Branches

on:
  schedule:
    - cron: '0 6 * * 1-5'
  workflow_dispatch:

permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v6.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          days-before-stale: 120
          days-before-delete: 180
          comment-updates: true
          max-issues: 20
          tag-committer: false
          stale-branch-label: '[AzurePlatform][stale branch 🗑️]'
          compare-branches: 'save'
